"""
A typical first message to a business ("I would like to book a table for
two tomorrow evening") in every language the AI disclosure is written in.
"""

FIRST_MESSAGES: dict[str, str] = {
    "ar": "مرحبا، هل يمكنني حجز طاولة لشخصين غدا؟",
    "az": "Salam, sabah axşam iki nəfərlik masa sifariş etmək istəyirəm",
    "be": "Добры дзень, ці можна заказаць столік на заўтра?",
    "bg": "Здравейте, може ли да запазя маса за двама за утре вечер?",
    "bn": "নমস্কার, আগামীকাল দুজনের জন্য একটি টেবিল বুক করতে চাই",
    "bs": "Zdravo, htio bih rezervisati sto za dvoje za sutra navečer",
    "ca": "Hola, voldria reservar una taula per a dues persones per demà",
    "cs": "Dobrý den, chtěl bych rezervovat stůl pro dva na zítra večer",
    "da": "Hej, jeg vil gerne bestille et bord til to personer i morgen aften",
    "de": "Guten Tag, ich möchte für morgen Abend einen Tisch für zwei reservieren",
    "el": "Γεια σας, θα ήθελα να κλείσω ένα τραπέζι για δύο αύριο",
    "en": "Hi, could I book a table for two tomorrow evening?",
    "es": "Hola, quisiera reservar una mesa para dos personas mañana por la noche",
    "et": "Tere, sooviksin broneerida laua kahele homme õhtul",
    "fa": "سلام، می‌خواهم برای فردا شب یک میز برای دو نفر رزرو کنم",
    "fi": "Hei, haluaisin varata pöydän kahdelle huomenna illalla",
    "fil": "Magandang araw po, gusto ko sanang magpareserba ng mesa bukas ng gabi",
    "fr": "Bonjour, je voudrais réserver une table pour deux personnes demain soir",
    "he": "שלום, אפשר להזמין שולחן לשניים למחר בערב?",
    "hi": "नमस्ते, मुझे कल शाम दो लोगों के लिए एक टेबल बुक करनी है",
    "hr": "Bok, htjela bih rezervirati stol za dvije osobe za sutra navečer",
    "hu": "Jó napot, szeretnék asztalt foglalni két főre holnap estére",
    "hy": "Բարև Ձեզ, կարո՞ղ եմ վաղը երեկոյան սեղան ամրագրել երկու հոգու համար",
    "id": "Halo, saya mau pesan meja untuk dua orang besok malam",
    "it": "Buongiorno, vorrei prenotare un tavolo per due persone domani sera",
    "ja": "こんにちは、明日の夜に二人で予約したいです",
    "ka": "გამარჯობა, ხვალ საღამოს ორ კაცზე მაგიდის დაჯავშნა მინდა",
    "kk": "Сәлеметсіз бе, ертең кешке екі адамға үстел брондағым келеді",
    "ko": "안녕하세요, 내일 저녁 두 명 예약하고 싶어요",
    "lt": "Laba diena, norėčiau rezervuoti staliuką dviem rytoj vakare",
    "lv": "Labdien, vēlos rezervēt galdiņu diviem rīt vakarā",
    "mk": "Здраво, би сакал да резервирам маса за двајца за утре вечер",
    "ms": "Helo, saya nak tempah meja untuk dua orang esok malam",
    "nb": "Hei, jeg vil gjerne bestille et bord til to personer i morgen kveld",
    "nl": "Hallo, ik wil graag een tafel reserveren voor twee personen morgenavond",
    "pl": "Dzień dobry, chciałbym zarezerwować stolik dla dwóch osób na jutro",
    "pt": "Olá, gostaria de reservar uma mesa para duas pessoas amanhã à noite",
    "ro": "Bună ziua, aș dori să rezerv o masă pentru două persoane mâine seară",
    "ru": "Здравствуйте, можно забронировать столик на двоих на завтра вечером?",
    "sk": "Dobrý deň, chcel by som rezervovať stôl pre dvoch na zajtra večer",
    "sl": "Pozdravljeni, rad bi rezerviral mizo za dva jutri zvečer",
    "sq": "Përshëndetje, dua të rezervoj një tavolinë për dy persona nesër në darkë",
    "sr": "Здраво, желео бих да резервишем сто за двоје за сутра увече",
    "sv": "Hej, jag skulle vilja boka ett bord för två personer i morgon kväll",
    "sw": "Habari, ningependa kuhifadhi meza ya watu wawili kesho jioni",
    "th": "สวัสดีครับ อยากจองโต๊ะสำหรับสองคนพรุ่งนี้เย็น",
    "tr": "Merhaba, yarın akşam iki kişilik bir masa ayırtmak istiyorum",
    "uk": "Добрий день, можна забронювати столик на двох на завтра ввечері?",
    "ur": "السلام علیکم، میں کل شام دو افراد کے لیے میز بک کرنا چاہتا ہوں",
    "uz": "Assalomu alaykum, ertaga kechqurun ikki kishilik stol band qilmoqchiman",
    "vi": "Xin chào, tôi muốn đặt bàn cho hai người vào tối mai",
    "zh": "你好，我想预订明天晚上两个人的桌子",
}
