"""
What the assistant says on the phone: greeting, recording notice, operator hint.

They exist for every language with text support: an English opener in
another language confuses customers and the autotest language check.

Every text exists for the languages businesses launch with; resolution
falls back to the base language and then English. `{business}` is replaced
with the business name (see `business_name_placeholder`).
"""

from app.schemas.dto.localization import LocalizedText
from app.utilities.localization.localized_texts import build_localized_text

CALL_GREETING: LocalizedText = build_localized_text(
    en="Hello! This is the AI assistant of {business}.",
    ru="Здравствуйте! Это AI-ассистент «{business}».",
    ka="გამარჯობა! ეს არის {business}-ის AI-ასისტენტი.",
    tr="Merhaba! {business} işletmesinin yapay zekâ asistanıyla görüşüyorsunuz.",
    he="שלום! כאן עוזר ה-AI של {business}.",
    ar="مرحبًا! معك مساعد الذكاء الاصطناعي لدى {business}.",
    hy="Բարև Ձեզ։ Ձեզ հետ խոսում է {business}-ի AI օգնականը։",
    uk="Вітаю! Це AI-асистент «{business}».",
    de="Hallo! Hier spricht der KI-Assistent von {business}.",
    fr="Bonjour ! Vous êtes en ligne avec l'assistant IA de {business}.",
    es="¡Hola! Le atiende el asistente de IA de {business}.",
    it="Buongiorno! Risponde l'assistente IA di {business}.",
    pt="Olá! Aqui é o assistente de IA de {business}.",
    pl="Dzień dobry! Mówi asystent AI {business}.",
    az="Salam! Bu, {business} müəssisəsinin süni intellekt köməkçisidir.",
    kk="Сәлеметсіз бе! Бұл — {business} компаниясының AI көмекшісі.",
    zh="您好！这里是{business}的AI助手。",
    ja="お電話ありがとうございます。{business}のAIアシスタントです。",
    be="Вітаю! Гэта AI-асістэнт «{business}».",
    bg="Здравейте! Тук е AI асистентът на {business}.",
    bn="হ্যালো! এটি {business}-এর AI সহকারী।",
    bs="Zdravo! Ovdje AI asistent {business}.",
    ca="Hola! Us atén l'assistent d'IA de {business}.",
    cs="Dobrý den! Tady AI asistent {business}.",
    da="Hej! Det er AI-assistenten hos {business}.",
    el="Γεια σας! Εδώ ο ψηφιακός βοηθός τεχνητής νοημοσύνης του {business}.",
    et="Tere! Siin on ettevõtte {business} tehisintellekti assistent.",
    fa="سلام! اینجا دستیار هوش مصنوعی {business} است.",
    fi="Hei! Täällä yrityksen {business} tekoälyavustaja.",
    fil="Kumusta! Ito ang AI assistant ng {business}.",
    hi="नमस्ते! यह {business} का AI सहायक है।",
    hr="Pozdrav! Ovdje AI asistent tvrtke {business}.",
    hu="Üdvözlöm! A(z) {business} mesterségesintelligencia-asszisztense beszél.",
    id="Halo! Ini asisten AI {business}.",
    ko="안녕하세요! {business}의 AI 어시스턴트입니다.",
    lt="Sveiki! Čia {business} dirbtinio intelekto asistentas.",
    lv="Sveiki! Šeit {business} mākslīgā intelekta asistents.",
    mk="Здраво! Ова е AI асистентот на {business}.",
    ms="Helo! Ini pembantu AI {business}.",
    nb="Hei! Dette er AI-assistenten til {business}.",
    nl="Hallo! U spreekt met de AI-assistent van {business}.",
    no="Hei! Dette er AI-assistenten til {business}.",
    ro="Bună ziua! Vă răspunde asistentul AI al {business}.",
    sk="Dobrý deň! Tu je AI asistent {business}.",
    sl="Pozdravljeni! Tukaj AI-asistent podjetja {business}.",
    sq="Përshëndetje! Ju flet asistenti i inteligjencës artificiale i {business}.",
    sr="Здраво! Овде AI асистент компаније {business}.",
    sv="Hej! Du pratar med AI-assistenten på {business}.",
    sw="Habari! Huyu ni msaidizi wa AI wa {business}.",
    th="สวัสดี! นี่คือผู้ช่วย AI ของ {business}",
    ur="السلام علیکم! یہ {business} کا AI معاون ہے۔",
    uz="Assalomu alaykum! Bu {business} AI yordamchisi.",
    vi="Xin chào! Đây là trợ lý AI của {business}.",
)

CALL_RECORDING_NOTICE: LocalizedText = build_localized_text(
    en="The call is recorded.",
    ru="Разговор записывается.",
    ka="საუბარი იწერება.",
    tr="Görüşme kaydedilmektedir.",
    he="השיחה מוקלטת.",
    ar="يتم تسجيل المكالمة.",
    hy="Զանգը ձայնագրվում է։",
    uk="Розмова записується.",
    de="Das Gespräch wird aufgezeichnet.",
    fr="L'appel est enregistré.",
    es="La llamada se está grabando.",
    it="La chiamata viene registrata.",
    pt="A ligação está sendo gravada.",
    pl="Rozmowa jest nagrywana.",
    az="Zəng qeydə alınır.",
    kk="Әңгіме жазылып жатыр.",
    zh="本次通话将被录音。",
    ja="この通話は録音されます。",
    be="Размова запісваецца.",
    bg="Разговорът се записва.",
    bn="এই কলটি রেকর্ড করা হচ্ছে।",
    bs="Poziv se snima.",
    ca="La trucada s'està enregistrant.",
    cs="Hovor je nahráván.",
    da="Opkaldet bliver optaget.",
    el="Η κλήση καταγράφεται.",
    et="Kõne salvestatakse.",
    fa="این تماس ضبط می\u200cشود.",
    fi="Puhelu nauhoitetaan.",
    fil="Nire-record ang tawag na ito.",
    hi="यह कॉल रिकॉर्ड की जा रही है।",
    hr="Poziv se snima.",
    hu="A hívást rögzítjük.",
    id="Panggilan ini direkam.",
    ko="이 통화는 녹음됩니다.",
    lt="Pokalbis įrašomas.",
    lv="Saruna tiek ierakstīta.",
    mk="Разговорот се снима.",
    ms="Panggilan ini dirakam.",
    nb="Samtalen blir tatt opp.",
    nl="Het gesprek wordt opgenomen.",
    no="Samtalen blir tatt opp.",
    ro="Apelul este înregistrat.",
    sk="Hovor sa nahráva.",
    sl="Klic se snema.",
    sq="Telefonata po regjistrohet.",
    sr="Позив се снима.",
    sv="Samtalet spelas in.",
    sw="Simu hii inarekodiwa.",
    th="การสนทนานี้มีการบันทึกเสียง",
    ur="یہ کال ریکارڈ کی جا رہی ہے۔",
    uz="Qo'ng'iroq yozib olinmoqda.",
    vi="Cuộc gọi này đang được ghi âm.",
)

CALL_OPERATOR_HINT: LocalizedText = build_localized_text(
    en='To talk to a staff member, say "operator".',
    ru="Чтобы поговорить с сотрудником, скажите «оператор».",
    ka="თანამშრომელთან სასაუბროდ თქვით „ოპერატორი“.",
    tr='Bir çalışanla görüşmek için "operatör" deyin.',
    he='כדי לדבר עם נציג, אמרו "נציג".',
    ar='للتحدث مع أحد الموظفين، قل "موظف".',
    hy="Աշխատակցի հետ խոսելու համար ասեք «օպերատոր»։",
    uk="Щоб поговорити з працівником, скажіть «оператор».",
    de="Um mit einem Mitarbeiter zu sprechen, sagen Sie „Mitarbeiter“.",
    fr="Pour parler à un membre de l'équipe, dites « opérateur ».",
    es="Para hablar con una persona del equipo, diga «operador».",
    it="Per parlare con un membro dello staff, dica «operatore».",
    pt='Para falar com um atendente, diga "atendente".',
    pl="Aby porozmawiać z pracownikiem, proszę powiedzieć „operator”.",
    az='Əməkdaşla danışmaq üçün "operator" deyin.',
    kk="Қызметкермен сөйлесу үшін «оператор» деп айтыңыз.",
    zh="如需人工服务，请说“人工”。",
    ja="スタッフとお話しになる場合は「オペレーター」とおっしゃってください。",
    be="Каб пагаварыць з супрацоўнікам, скажыце «аператар».",
    bg="За да говорите със служител, кажете „оператор“.",
    bn="কর্মীর সঙ্গে কথা বলতে “অপারেটর” বলুন।",
    bs="Da razgovarate sa zaposlenikom, recite „operater“.",
    ca="Per parlar amb una persona de l'equip, digueu «operador».",
    cs="Pro hovor se zaměstnancem řekněte „operátor“.",
    da="Sig „medarbejder“ for at tale med en medarbejder.",
    el="Για να μιλήσετε με έναν υπάλληλο, πείτε «υπάλληλος».",
    et="Töötajaga rääkimiseks öelge „operaator“.",
    fa="برای صحبت با کارمند، بگویید «اپراتور».",
    fi="Jos haluat puhua henkilökunnan kanssa, sano ”asiakaspalvelu”.",
    fil="Para makausap ang isang staff, sabihin ang “operator”.",
    hi="किसी कर्मचारी से बात करने के लिए “ऑपरेटर” कहें।",
    hr="Za razgovor s djelatnikom recite „operater”.",
    hu="Ha munkatárssal szeretne beszélni, mondja: „operátor”.",
    id="Untuk berbicara dengan staf, ucapkan “operator”.",
    ko="직원과 통화하시려면 “상담원”이라고 말씀해 주세요.",
    lt="Norėdami kalbėti su darbuotoju, pasakykite „operatorius“.",
    lv="Lai runātu ar darbinieku, sakiet “operators”.",
    mk="За да зборувате со вработен, кажете „оператор“.",
    ms="Untuk bercakap dengan kakitangan, sebut “operator”.",
    nb="Si «operatør» for å snakke med en ansatt.",
    nl="Zeg “medewerker” om met een medewerker te spreken.",
    no="Si «operatør» for å snakke med en ansatt.",
    ro="Pentru a vorbi cu un angajat, spuneți „operator”.",
    sk="Ak chcete hovoriť so zamestnancom, povedzte „operátor“.",
    sl="Za pogovor z zaposlenim recite »operater«.",
    sq="Për të folur me një punonjës, thoni “operator”.",
    sr="Да бисте разговарали са запосленим, реците „оператер“.",
    sv="Säg ”personal” för att prata med en medarbetare.",
    sw="Ili kuzungumza na mfanyakazi, sema “opereta”.",
    th="หากต้องการคุยกับพนักงาน กรุณาพูดว่า “พนักงาน”",
    ur="کسی ملازم سے بات کرنے کے لیے “آپریٹر” کہیں۔",
    uz="Xodim bilan gaplashish uchun “operator” deng.",
    vi="Để nói chuyện với nhân viên, hãy nói “tổng đài viên”.",
)
