"""
The label of the button that opens a WhatsApp list of options (at most 20
characters), in the language the options are written in; resolution falls
back to the base language and then English.
"""

from app.schemas.dto.localization import LocalizedText
from app.utilities.localization.localized_texts import build_localized_text

CHOICE_LIST_BUTTON: LocalizedText = build_localized_text(
    en="Choose",
    ru="Выбрать",
    ka="არჩევა",
    tr="Seçin",
    he="בחירה",
    ar="اختر",
    hy="Ընտրել",
    uk="Обрати",
    de="Auswählen",
    fr="Choisir",
    es="Elegir",
    it="Scegli",
    pt="Escolher",
    pl="Wybierz",
    az="Seçin",
    kk="Таңдау",
    zh="选择",
    ja="選択",
    be="Выбраць",
    bg="Изберете",
    bn="বেছে নিন",
    bs="Odaberite",
    ca="Tria",
    cs="Vybrat",
    da="Vælg",
    el="Επιλογή",
    et="Vali",
    fa="انتخاب",
    fi="Valitse",
    fil="Pumili",
    hi="चुनें",
    hr="Odaberite",
    hu="Válasszon",
    id="Pilih",
    ko="선택",
    lt="Pasirinkti",
    lv="Izvēlēties",
    mk="Изберете",
    ms="Pilih",
    nb="Velg",
    nl="Kies",
    no="Velg",
    ro="Alegeți",
    sk="Vybrať",
    sl="Izberite",
    sq="Zgjidhni",
    sr="Изаберите",
    sv="Välj",
    sw="Chagua",
    th="เลือก",
    ur="منتخب کریں",
    uz="Tanlang",
    vi="Chọn",
)
