"""Number words of English, German and Turkish."""

from app.utilities.reply_guard.number_word_lexicon import NumberWordLexicon

ENGLISH_NUMBER_WORDS: NumberWordLexicon = NumberWordLexicon(
    values={
        "one": 1,
        "two": 2,
        "three": 3,
        "four": 4,
        "five": 5,
        "six": 6,
        "seven": 7,
        "eight": 8,
        "nine": 9,
        "ten": 10,
        "eleven": 11,
        "twelve": 12,
        "thirteen": 13,
        "fourteen": 14,
        "fifteen": 15,
        "sixteen": 16,
        "seventeen": 17,
        "eighteen": 18,
        "nineteen": 19,
        "twenty": 20,
        "thirty": 30,
        "forty": 40,
        "fifty": 50,
        "sixty": 60,
        "seventy": 70,
        "eighty": 80,
        "ninety": 90,
    },
    multipliers={
        "hundred": 100,
        "thousand": 1000,
        "million": 1_000_000,
    },
    joiners=frozenset({"-"}),
    connectors=frozenset({"and"}),
    article_words=frozenset({"a"}),
)

GERMAN_NUMBER_WORDS: NumberWordLexicon = NumberWordLexicon(
    values={
        "ein": 1,
        "eins": 1,
        "eine": 1,
        "einen": 1,
        "einem": 1,
        "zwei": 2,
        "zwo": 2,
        "drei": 3,
        "vier": 4,
        "fünf": 5,
        "fuenf": 5,
        "sechs": 6,
        "sieben": 7,
        "acht": 8,
        "neun": 9,
        "zehn": 10,
        "elf": 11,
        "zwölf": 12,
        "zwoelf": 12,
        "dreizehn": 13,
        "vierzehn": 14,
        "fünfzehn": 15,
        "fuenfzehn": 15,
        "sechzehn": 16,
        "siebzehn": 17,
        "achtzehn": 18,
        "neunzehn": 19,
        "zwanzig": 20,
        "dreißig": 30,
        "dreissig": 30,
        "vierzig": 40,
        "fünfzig": 50,
        "fuenfzig": 50,
        "sechzig": 60,
        "siebzig": 70,
        "achtzig": 80,
        "neunzig": 90,
    },
    multipliers={
        "hundert": 100,
        "tausend": 1000,
        "million": 1_000_000,
        "millionen": 1_000_000,
    },
    # "fünfundzwanzig", "zweihundertfünfzig": parts glue into one word.
    joiners=frozenset({"und", "-"}),
    connectors=frozenset({"und"}),
    is_unit_before_tens=True,
)

TURKISH_NUMBER_WORDS: NumberWordLexicon = NumberWordLexicon(
    values={
        "bir": 1,
        "iki": 2,
        "üç": 3,
        "dört": 4,
        "beş": 5,
        "altı": 6,
        "yedi": 7,
        "sekiz": 8,
        "dokuz": 9,
        "on": 10,
        "yirmi": 20,
        "otuz": 30,
        "kırk": 40,
        "elli": 50,
        "altmış": 60,
        "yetmiş": 70,
        "seksen": 80,
        "doksan": 90,
    },
    multipliers={
        "yüz": 100,
        "bin": 1000,
        "milyon": 1_000_000,
    },
    joiners=frozenset({"-"}),
    # "yüzde" (percent) is not "yüz" (hundred) with the ending "-de".
    non_numbers=frozenset({"yüzde"}),
    # Case endings of a number ("yedide": at seven, "elliye": for fifty).
    endings=frozenset(
        {
            "a",
            "e",
            "ya",
            "ye",
            "da",
            "de",
            "ta",
            "te",
            "dan",
            "den",
            "tan",
            "ten",
            "ı",
            "i",
            "u",
            "ü",
            "yı",
            "yi",
            "yu",
            "yü",
            "lık",
            "lik",
            "luk",
            "lük",
        }
    ),
)
