"""Number words of French and Spanish."""

from app.utilities.reply_guard.number_word_lexicon import NumberWordLexicon

FRENCH_NUMBER_WORDS: NumberWordLexicon = NumberWordLexicon(
    values={
        "un": 1,
        "une": 1,
        "deux": 2,
        "trois": 3,
        "quatre": 4,
        "cinq": 5,
        "six": 6,
        "sept": 7,
        "huit": 8,
        "neuf": 9,
        "dix": 10,
        "onze": 11,
        "douze": 12,
        "treize": 13,
        "quatorze": 14,
        "quinze": 15,
        "seize": 16,
        "vingt": 20,
        "trente": 30,
        "quarante": 40,
        "cinquante": 50,
        "soixante": 60,
        # "quatre-vingts" is one value, "quatre-vingt-dix" 80 + 10.
        "quatre-vingt": 80,
        "quatre-vingts": 80,
        "septante": 70,
        "huitante": 80,
        "octante": 80,
        "nonante": 90,
    },
    multipliers={
        "cent": 100,
        "cents": 100,
        "mille": 1000,
        "million": 1_000_000,
        "millions": 1_000_000,
    },
    # "vingt-et-un" (the 1990 spelling) glues "et" between hyphens.
    joiners=frozenset({"-", "et"}),
    connectors=frozenset({"et"}),
    article_words=frozenset({"un"}),
    # "soixante et onze" (71), "quatre-vingt-quinze" (95).
    is_tens_before_teens=True,
)

SPANISH_NUMBER_WORDS: NumberWordLexicon = NumberWordLexicon(
    values={
        "un": 1,
        "uno": 1,
        "una": 1,
        "dos": 2,
        "tres": 3,
        "cuatro": 4,
        "cinco": 5,
        "seis": 6,
        "siete": 7,
        "ocho": 8,
        "nueve": 9,
        "diez": 10,
        "once": 11,
        "doce": 12,
        "trece": 13,
        "catorce": 14,
        "quince": 15,
        "dieciséis": 16,
        "dieciseis": 16,
        "diecisiete": 17,
        "dieciocho": 18,
        "diecinueve": 19,
        "veinte": 20,
        "veintiuno": 21,
        "veintiún": 21,
        "veintiuna": 21,
        "veintidós": 22,
        "veintidos": 22,
        "veintitrés": 23,
        "veintitres": 23,
        "veinticuatro": 24,
        "veinticinco": 25,
        "veintiséis": 26,
        "veintiseis": 26,
        "veintisiete": 27,
        "veintiocho": 28,
        "veintinueve": 29,
        "treinta": 30,
        "cuarenta": 40,
        "cincuenta": 50,
        "sesenta": 60,
        "setenta": 70,
        "ochenta": 80,
        "noventa": 90,
        "cien": 100,
        "ciento": 100,
        "doscientos": 200,
        "doscientas": 200,
        "trescientos": 300,
        "trescientas": 300,
        "cuatrocientos": 400,
        "cuatrocientas": 400,
        "quinientos": 500,
        "quinientas": 500,
        "seiscientos": 600,
        "seiscientas": 600,
        "setecientos": 700,
        "setecientas": 700,
        "ochocientos": 800,
        "ochocientas": 800,
        "novecientos": 900,
        "novecientas": 900,
    },
    multipliers={
        "mil": 1000,
        "millón": 1_000_000,
        "millon": 1_000_000,
        "millones": 1_000_000,
    },
    joiners=frozenset({"-"}),
    connectors=frozenset({"y"}),
)
