"""
Thousands of rows in the hot-path tables, generated by Postgres itself.

Only the fields the lookup columns and key triggers read are filled: the
query-plan tests never decode these rows, they need realistic table sizes
and value spreads for the planner (30 businesses, many contacts and
conversations each, as a busy platform has).
"""

from dataclasses import dataclass

from psycopg import sql

from app.clients.postgres.postgres_connection_pool_client import (
    PostgresConnectionPoolClient,
)
from app.schemas.typings.businesses.prefixed_id import BusinessId
from tests.storage.hot_path_seeding import BYPASS_RLS

ROWS_PER_TABLE: int = 4_000
BUSINESS_COUNT: int = 30
BASE_TIME: int = 1_790_000_000_000_000


@dataclass(frozen=True)
class SeededTable:
    """A table and the SQL of one generated document (`n` is the row number)."""

    name: str
    document_sql: str
    has_business: bool = True


SEEDED_TABLES: tuple[SeededTable, ...] = (
    SeededTable(
        "users",
        "jsonb_build_object('phone_number', '+1555' || lpad(n::text, 7, '0'), "
        "'email', 'user' || n || '@example.com')",
        has_business=False,
    ),
    SeededTable(
        "user_sessions",
        "jsonb_build_object('token_hash', md5(n::text), 'expires_at', %(time)s + n)",
        has_business=False,
    ),
    SeededTable(
        "otp_challenges",
        "jsonb_build_object('created_at', %(time)s + n * 1000)",
        has_business=False,
    ),
    SeededTable(
        "businesses",
        "jsonb_build_object('members', jsonb_build_array("
        "jsonb_build_object('user_id', 'seeded_user_' || n, 'role', 'owner')))",
    ),
    SeededTable(
        "channels",
        "jsonb_build_object('kind', (array['telegram', 'whatsapp', 'instagram'])"
        "[1 + n %% 3], 'external_id', 'external_' || n)",
    ),
    SeededTable(
        "contacts",
        "jsonb_build_object('phone_number', '+995555' || lpad(n::text, 6, '0'), "
        "'verified_phone_number', '+995555' || lpad(n::text, 6, '0'), "
        "'channel_identities', jsonb_build_array(jsonb_build_object("
        "'channel', 'telegram', 'channel_user_id', 'tg_' || n)))",
    ),
    SeededTable(
        "conversations",
        "jsonb_build_object('contact_id', 'seeded_contact_' || (n %% 1000), "
        "'channel_user_id', 'tg_' || n, 'status', 'open', "
        "'last_message_at', %(time)s + n)",
    ),
    SeededTable(
        "messages",
        "jsonb_build_object('conversation_id', 'seeded_conversation_' || (n %% 800), "
        "'direction', (array['inbound', 'outbound'])[1 + n %% 2], "
        "'author', (array['customer', 'assistant'])[1 + n %% 2], "
        "'created_at', %(time)s + n)",
    ),
    SeededTable(
        "llm_turns",
        "jsonb_build_object('conversation_id', 'seeded_conversation_' || (n %% 800), "
        "'sequence_number', n)",
        has_business=False,
    ),
    SeededTable(
        "calls",
        "jsonb_build_object('provider_call_id', 'call_' || n)",
    ),
    SeededTable(
        "usage_events",
        "jsonb_build_object('occurred_at', %(time)s + n * 1000)",
    ),
    SeededTable(
        "manager_telegram_links",
        "jsonb_build_object('code_hash', md5('link' || n))",
    ),
    SeededTable(
        "channel_message_receipts",
        "jsonb_build_object('channel', 'telegram', "
        "'provider_message_id', 'message_' || n, 'created_at', %(time)s + n)",
    ),
)


def seed_hot_path_tables(
    connection_pool: PostgresConnectionPoolClient,
    business_ids: list[BusinessId],
) -> None:
    """ROWS_PER_TABLE rows in every hot-path table, spread over the businesses."""

    with connection_pool.transaction() as connection:
        connection.execute(BYPASS_RLS)
        for table in SEEDED_TABLES:
            business_sql: str = (
                "(%(businesses)s::text[])[1 + n %% %(business_count)s]"
                if table.has_business
                else "null"
            )
            statement: str = (
                "insert into {table} "
                "(document_key, business_id, document, created_at, updated_at) "
                f"select 'seeded_' || n, {business_sql}, {table.document_sql}, n, n "
                "from generate_series(1, %(rows)s) as n"
            )
            connection.execute(
                sql.SQL(statement).format(  # pyright: ignore[reportArgumentType]
                    table=sql.Identifier("workshop", table.name)
                ),
                {
                    "businesses": [str(business_id) for business_id in business_ids],
                    "business_count": len(business_ids),
                    "rows": ROWS_PER_TABLE,
                    "time": BASE_TIME,
                },
            )
