"""
Many rows fast, and the SQL the application runs: helpers of the storage
tests that check query plans and timings on realistic table sizes.
"""

from collections.abc import Callable, Generator, Sequence
from contextlib import contextmanager
from typing import LiteralString, cast

from base_pydantic_schemas import PersistentDocument
from psycopg import sql
from psycopg.rows import TupleRow

from app.adapters.storage.postgres.postgres_session_settings import (
    DOCUMENT_SCHEMA_NAME,
)
from app.clients.postgres.postgres_connection_pool_client import (
    PostgresConnection,
    PostgresConnectionPoolClient,
)
from app.schemas.typings.platform.strings import DatabaseUrl
from app.utilities.storage.document_tenancy import read_document_business_id

BYPASS_RLS: LiteralString = "select set_config('app.bypass_rls', 'on', true)"


def insert_documents(
    connection_pool: PostgresConnectionPoolClient,
    table_name: str,
    documents: Sequence[PersistentDocument],
    key_of: Callable[[PersistentDocument], str] = lambda document: str(
        getattr(document, "id")  # noqa: B009 - every seeded document has an id
    ),
) -> None:
    """Insert documents in one transaction, as the collection would store them."""

    statement = sql.SQL(
        "insert into {table} "
        "(document_key, business_id, document, created_at, updated_at) "
        "values (%s, %s, %s::jsonb, %s, %s)"
    ).format(table=sql.Identifier(DOCUMENT_SCHEMA_NAME, table_name))
    rows: list[tuple[str, str | None, str, int, int]] = []
    for position, document in enumerate(documents):
        business_id = read_document_business_id(document)
        rows.append(
            (
                key_of(document),
                None if business_id is None else str(business_id),
                document.model_dump_json(),
                position,
                position,
            )
        )

    with connection_pool.transaction() as connection:
        connection.execute(BYPASS_RLS)
        with connection.cursor() as cursor:
            cursor.executemany(statement, rows)


def insert_session_rows(
    connection_pool: PostgresConnectionPoolClient,
    count: int,
    expires_at: int,
) -> None:
    """`count` sessions of other users, generated by Postgres itself."""

    with connection_pool.transaction() as connection:
        connection.execute(BYPASS_RLS)
        connection.execute(
            "insert into workshop.user_sessions "
            "(document_key, business_id, document, created_at, updated_at) "
            "select 'seeded_' || n, null, jsonb_build_object("
            "'id', 'seeded_' || n, 'user_id', 'seeded_user_' || n, "
            "'token_hash', md5(n::text), 'expires_at', %s::bigint + n), n, n "
            "from generate_series(1, %s) as n",
            (expires_at, count),
        )


def analyze(connection_pool: PostgresConnectionPoolClient) -> None:
    """
    Fresh planner statistics and visibility map, as autovacuum leaves the
    seeded tables (too slow to wait for in a test). Vacuuming here, not only
    analyzing, keeps the plans the same whether or not autovacuum reached a
    table before the test ran: on a vacuumed table index-only scans of the
    covering indexes cost less, and a busy machine runs the test later.
    """

    with connection_pool.connection() as connection:
        connection.execute("vacuum analyze")


class RecordingConnection:
    """A connection that remembers every statement run through it."""

    def __init__(
        self,
        connection: PostgresConnection,
        transaction: list[tuple[str, Sequence[object]]],
    ) -> None:
        self._connection: PostgresConnection = connection
        self._transaction: list[tuple[str, Sequence[object]]] = transaction

    def execute(
        self,
        query: str | sql.Composable,
        parameters: Sequence[object] | None = None,
    ) -> object:
        text: str = (
            query if isinstance(query, str) else query.as_string(self._connection)
        )
        recorded: tuple[object, ...] = () if parameters is None else tuple(parameters)
        self._transaction.append((text, recorded))
        return self._connection.execute(text, recorded or None)  # pyright: ignore[reportArgumentType, reportCallIssue]


class RecordingConnectionPool(PostgresConnectionPoolClient):
    """A pool that records the statements of every transaction it hands out."""

    def __init__(self, database_url: DatabaseUrl) -> None:
        super().__init__(database_url, max_size=2)
        self.transactions: list[list[tuple[str, Sequence[object]]]] = []

    @contextmanager
    def transaction(self) -> Generator[PostgresConnection]:
        statements: list[tuple[str, Sequence[object]]] = []
        self.transactions.append(statements)
        with super().transaction() as connection:
            yield cast(PostgresConnection, RecordingConnection(connection, statements))


def explain(
    connection_pool: PostgresConnectionPoolClient,
    transaction: Sequence[tuple[str, Sequence[object]]],
) -> list[dict[str, object]]:
    """
    The plans (EXPLAIN, format json) of the reads and deletes of one
    recorded transaction, replayed after its scope settings.
    """

    plans: list[dict[str, object]] = []
    with connection_pool.transaction() as connection:
        for statement, parameters in transaction:
            # Replays SQL the application composed itself (sql.SQL objects).
            replayed: LiteralString = statement  # pyright: ignore[reportAssignmentType]
            if "set_config" in statement:
                connection.execute(replayed, parameters or None)
                continue

            row: TupleRow | None = connection.execute(
                f"explain (format json) {replayed}", parameters or None
            ).fetchone()
            assert row is not None
            plan: object = cast(list[dict[str, object]], row[0])[0]["Plan"]
            plans.append(cast(dict[str, object], plan))

    return plans


def plan_nodes(plan: dict[str, object]) -> list[dict[str, object]]:
    """A plan node and all nodes below it."""

    nodes: list[dict[str, object]] = [plan]
    for child in cast(list[dict[str, object]], plan.get("Plans", [])):
        nodes.extend(plan_nodes(child))

    return nodes
