"""
Thousands of rows in the tables of the cabinet's lists and the dashboard,
generated by Postgres itself.

Only the fields the lookup columns read are filled: the query-plan tests
replay the SQL the repositories run (rows that do not decode are fine
there), they need realistic table sizes and value spreads for the planner.
"""

from typing import LiteralString

from psycopg import sql

from app.clients.postgres.postgres_connection_pool_client import (
    PostgresConnectionPoolClient,
)
from app.schemas.typings.businesses.prefixed_id import BusinessId
from tests.storage.hot_path_rows import BASE_TIME, SeededTable
from tests.storage.hot_path_seeding import BYPASS_RLS

LIST_ROWS: int = 30_000
LIST_BUSINESS_COUNT: int = 10
FLAG: LiteralString = "(array[false, false, false, true])[1 + n %% 4]"
# A conversation id (a UUID v4 made from n mod 900) of 900 conversations.
CONVERSATION: LiteralString = (
    "'conversation_' || (substr(md5((n %% 900)::text), 1, 12) || '4' || "
    "substr(md5((n %% 900)::text), 14, 3) || 'a' || "
    "substr(md5((n %% 900)::text), 18, 15))::uuid"
)

# The customer of a booking or a lead (one of 1,000) and where it came from.
CUSTOMER: LiteralString = (
    "'contact_id', 'seeded_contact_' || (n %% 1000), "
    "'source_channel', (array['telegram', 'whatsapp', 'phone'])[1 + n %% 3]"
)

LIST_TABLES: tuple[SeededTable, ...] = (
    SeededTable(
        "conversations",
        "jsonb_build_object('contact_id', 'seeded_contact_' || (n %% 1000), "
        "'channel_user_id', 'tg_' || n, "
        "'status', (array['open', 'handoff', 'closed'])[1 + n %% 3], "
        "'channel', (array['telegram', 'whatsapp', 'web_chat'])[1 + n %% 3], "
        "'language', (array['ka', 'en', 'ru'])[1 + n %% 3], "
        f"'is_after_hours', {FLAG}, 'is_sandbox', {FLAG}, "
        "'created_at', %(time)s + n * 1000, 'last_message_at', %(time)s + n * 2000)",
    ),
    SeededTable(
        "messages",
        f"jsonb_build_object('conversation_id', {CONVERSATION}, "
        "'direction', (array['inbound', 'outbound'])[1 + n %% 2], "
        "'author', (array['customer', 'assistant'])[1 + n %% 2], "
        "'input_tokens', n %% 50, 'output_tokens', n %% 20, "
        "'cost_micro_usd', n %% 300, 'created_at', %(time)s + n * 1000, "
        "'tool_calls', case when n %% 25 = 0 then jsonb_build_array("
        "jsonb_build_object('is_error', n %% 50 = 0)) else '[]'::jsonb end)",
    ),
    SeededTable(
        "bookings",
        f"jsonb_build_object('conversation_id', {CONVERSATION}, {CUSTOMER}, "
        "'status', (array['confirmed', 'pending', 'cancelled', 'completed'])"
        "[1 + n %% 4], 'resource_id', 'resource_' || (n %% 7), "
        f"'is_sandbox', {FLAG}, 'starts_at', 1790000000 + n * 600, "
        "'ends_at', 1790000000 + n * 600 + 3600, 'created_at', %(time)s + n * 1000)",
    ),
    SeededTable(
        "leads",
        f"jsonb_build_object('conversation_id', {CONVERSATION}, {CUSTOMER}, "
        "'status', (array['new', 'in_progress', 'won', 'lost'])[1 + n %% 4], "
        f"'is_sandbox', {FLAG}, 'created_at', %(time)s + n * 1000)",
    ),
    SeededTable(
        "handoffs",
        f"jsonb_build_object('conversation_id', {CONVERSATION}, "
        "'status', (array['resolved', 'resolved', 'resolved', 'notified'])"
        "[1 + n %% 4], 'urgency', (array['low', 'normal', 'high', 'critical'])"
        "[1 + n %% 4], 'reason', 'complaint', "
        f"'is_sandbox', {FLAG}, 'created_at', %(time)s + n * 1000, "
        "'resolved_at', case when n %% 4 < 3 then %(time)s + n * 1500 end)",
    ),
    SeededTable(
        "unanswered_questions",
        "jsonb_build_object('occurrence_count', 1 + n %% 9, "
        "'last_seen_at', %(time)s + n * 1000, 'is_resolved', n %% 3 = 0, "
        f"'is_sandbox', {FLAG})",
    ),
    SeededTable(
        "contacts",
        "jsonb_build_object('name', 'Customer ' || n, "
        "'display_name_folded', 'customer ' || n, "
        "'last_seen_at', %(time)s + n * 1000)",
    ),
    SeededTable(
        "knowledge_items",
        "jsonb_build_object('title', 'Item ' || n, "
        "'kind', (array['menu_item', 'faq', 'service', 'policy'])[1 + n %% 4], "
        "'is_active', n %% 5 <> 0, 'updated_at', %(time)s + n * 1000)",
    ),
    SeededTable(
        "audit_log_entries",
        "jsonb_build_object('actor_id', 'seeded_user_' || (n %% 12), "
        "'action', (array['view', 'export', 'delete'])[1 + n %% 3], "
        "'entity', (array['conversation', 'booking', 'contact'])[1 + n %% 3], "
        "'created_at', %(time)s + n * 1000)",
    ),
)


def seed_list_tables(
    connection_pool: PostgresConnectionPoolClient,
    business_ids: list[BusinessId],
    tables: tuple[SeededTable, ...] = LIST_TABLES,
) -> None:
    """LIST_ROWS rows in every table, spread over the businesses."""

    with connection_pool.transaction() as connection:
        connection.execute(BYPASS_RLS)
        for table in tables:
            statement: LiteralString = (
                "insert into {table} "
                "(document_key, business_id, document, created_at, updated_at) "
                "select 'seeded_' || n, "
                "(%(businesses)s::text[])[1 + n %% %(business_count)s], "
                f"{table.document_sql}, n, n "
                "from generate_series(1, %(rows)s) as n"
            )
            connection.execute(
                sql.SQL(statement).format(table=sql.Identifier("workshop", table.name)),
                {
                    "businesses": [str(business_id) for business_id in business_ids],
                    "business_count": len(business_ids),
                    "rows": LIST_ROWS,
                    "time": BASE_TIME,
                },
            )
