"""
The words a customer sends, as the whole message, to stop (or to start
again) the messages they did not ask for: reminders, feedback requests,
messages after a missed call. Kept in their normalized form
(`opt_out.normalize_command`): lower case, no surrounding punctuation,
hyphens as spaces. "Cancel" is left out on purpose: customers write it
about their booking.
"""

OPT_OUT_KEYWORDS: frozenset[str] = frozenset(
    {
        # English and the carriers' common set.
        "stop",
        "stop all",
        "stopall",
        "unsubscribe",
        "opt out",
        "optout",
        "end messages",
        # Russian, Ukrainian, Belarusian, Kazakh, Kyrgyz.
        "стоп",
        "отписаться",
        "отписка",
        "отпишите",
        "отпишите меня",
        "не пишите",
        "не пишите мне",
        "відписатися",
        "відписка",
        "не пишіть",
        "адпісацца",
        "тоқтат",
        "тоқтату",
        "токтот",
        # Georgian, Armenian, Azerbaijani.
        "სტოპ",
        "შეწყვეტა",
        "გამოწერის გაუქმება",
        "ნუ მწერთ",
        "ստոպ",
        "դադարեցնել",
        "dayan",
        "dayandır",
        "abunəlikdən çıx",
        # Turkish, Uzbek.
        "dur",
        "durdur",
        "abonelikten çık",
        "to'xtat",
        "toxtat",
        # German, Dutch, Scandinavian, Finnish.
        "stopp",
        "abmelden",
        "abbestellen",
        "afmelden",
        "uitschrijven",
        "avsluta",
        "avmeld",
        "afmeld",
        "lopeta",
        # French, Spanish, Italian, Portuguese, Romanian.
        "arret",
        "arrêt",
        "désabonner",
        "desabonner",
        "désinscrire",
        "parar",
        "baja",
        "darme de baja",
        "basta",
        "disiscriviti",
        "cancellami",
        "sair",
        "descadastrar",
        "dezabonare",
        # Polish, Czech, Slovak, Hungarian, Balkan languages, Greek.
        "wypisz",
        "rezygnuję",
        "odhlásit",
        "odhlasit",
        "odhlásiť",
        "leiratkozás",
        "leiratkozom",
        "odjava",
        "отписване",
        "στοπ",
        "διακοπή",
        # Hebrew, Arabic, Persian.
        "עצור",
        "הסר",
        "הפסק",
        "סטופ",
        "توقف",
        "ايقاف",
        "إيقاف",
        "الغاء الاشتراك",
        "إلغاء الاشتراك",
        "لغو",
        "توقف کن",
        # Asian languages.
        "退订",
        "取消订阅",
        "td",
        "配信停止",
        "停止",
        "수신거부",
        "हटाएं",
        "बंद करें",
        "dừng",
        "berhenti",
        "hentikan",
    }
)

OPT_IN_KEYWORDS: frozenset[str] = frozenset(
    {
        "start",
        "unstop",
        "subscribe",
        "resume",
        "старт",
        "подписаться",
        "підписатися",
        "სტარტი",
        "გამოწერა",
        "ստարտ",
        "başla",
        "starten",
        "anmelden",
        "démarrer",
        "reprendre",
        "alta",
        "reanudar",
        "iniciar",
        "riprendi",
        "התחל",
        "ابدأ",
        "订阅",
        "配信再開",
        "수신동의",
    }
)
