/** Drafts of the hosted chat's privacy notice in northern and eastern European widget languages (needs_review). */

import type { PrivacyNoticeDraft } from "./noticeTypes";

export const DRAFTS_EUROPE_NORTH_EAST: Readonly<Record<string, PrivacyNoticeDraft>> = {
  lt: {
    status: "needs_review",
    texts: {
      title: "Privatumo pranešimas",
      subtitle: "Kaip {business} tvarko tai, ką rašote jo pokalbyje",
      whoTitle: "Kas atsako",
      who: "{business} į žinutes atsako dirbtinio intelekto asistentu – savo svetainėje, šiame puslapyje ir pokalbių programėlėse. Assistant Workshop teikia asistentą ir tvarko jūsų žinutes {business} vardu; {business} sprendžia, kas su jomis daroma.",
      whatTitle: "Kas saugoma",
      whatMessages: "Tai, ką rašote pokalbyje, ir asistento atsakymai.",
      whatContacts: "Jūsų vardas, telefono numeris ar el. paštas, jei juos nurodote (pavyzdžiui, rezervacijai ar atskambinimui).",
      whatBrowser: "Atsitiktinis raktas naršyklės saugykloje, kad pokalbis tęstųsi ten, kur jį palikote. Pokalbis nenaudoja slapukų.",
      whatTechnical: "Techniniai duomenys, pavyzdžiui, IP adresas, trumpai saugomi pokalbiui apsaugoti nuo piktnaudžiavimo.",
      whyTitle: "Kam",
      why: "Kad atsakytume į jūsų klausimus, priimtume rezervacijas ir užklausas bei perduotume pokalbį {business} darbuotojams, kai paprašote žmogaus arba asistentas negali padėti.",
      sharedTitle: "Kas tai mato",
      shared: "{business} darbuotojai. Atsakymams parašyti pokalbio tekstą tvarko DI modelio, kuriuo veikia asistentas, teikėjas – tik šiam tikslui.",
      keptTitle: "Kiek laiko",
      kept: "{business} sprendžia, kiek laiko saugomi pokalbiai. Bet kada galite paprašyti ištrinti jūsiškį.",
      rightsTitle: "Jūsų pasirinkimai",
      rights: "Galite paklausti {business}, ką apie jus saugo, ir paprašyti tai ištaisyti ar ištrinti: parašykite pokalbyje arba susisiekite su įmone tiesiogiai. Asistentas gali klysti, todėl svarbias detales (kainas, laiką) pasitikslinkite įmonėje.",
      platformNote: "Tai numatytasis Assistant Workshop platformos pranešimas. {business} gali paskelbti savo.",
      backToChat: "Grįžti į pokalbį",
      draftNote: "Šis vertimas yra dar neperžiūrėtas juodraštis; vadovaujamasi tekstu anglų kalba.",
      readInEnglish: "Skaityti angliškai",
    },
  },
  lv: {
    status: "needs_review",
    texts: {
      title: "Privātuma paziņojums",
      subtitle: "Kā {business} rīkojas ar to, ko rakstāt tā tērzēšanā",
      whoTitle: "Kas atbild",
      who: "{business} atbild uz ziņām ar mākslīgā intelekta asistentu – savā vietnē, šajā lapā un ziņapmaiņas lietotnēs. Assistant Workshop nodrošina asistentu un apstrādā jūsu ziņas {business} vārdā; {business} lemj, kas ar tām notiek.",
      whatTitle: "Kas tiek glabāts",
      whatMessages: "Tas, ko rakstāt tērzēšanā, un asistenta atbildes.",
      whatContacts: "Jūsu vārds, tālruņa numurs vai e-pasts, ja tos norādāt (piemēram, rezervācijai vai atzvanīšanai).",
      whatBrowser: "Nejaušs atslēgas kods pārlūka krātuvē, lai tērzēšana turpinātos tur, kur to pārtraucāt. Tērzēšana neizmanto sīkdatnes.",
      whatTechnical: "Tehniskie dati, piemēram, IP adrese, ko īsu laiku glabā, lai pasargātu tērzēšanu no ļaunprātīgas izmantošanas.",
      whyTitle: "Kāpēc",
      why: "Lai atbildētu uz jūsu jautājumiem, pieņemtu rezervācijas un pieprasījumus un nodotu sarunu {business} darbiniekiem, ja lūdzat cilvēku vai asistents nevar palīdzēt.",
      sharedTitle: "Kas to redz",
      shared: "{business} darbinieki. Lai uzrakstītu atbildes, sarunas tekstu apstrādā MI modeļa nodrošinātājs, uz kura darbojas asistents, – tikai šim nolūkam.",
      keptTitle: "Cik ilgi",
      kept: "{business} lemj, cik ilgi sarunas tiek glabātas. Jebkurā brīdī varat lūgt dzēst savējo.",
      rightsTitle: "Jūsu izvēles",
      rights: "Varat jautāt {business}, ko tas par jums glabā, un lūgt to labot vai dzēst: rakstiet tērzēšanā vai sazinieties ar uzņēmumu tieši. Asistents var kļūdīties, tāpēc svarīgas detaļas (cenas, laikus) pārbaudiet uzņēmumā.",
      platformNote: "Šis ir Assistant Workshop platformas noklusējuma paziņojums. {business} var publicēt savu.",
      backToChat: "Atpakaļ uz tērzēšanu",
      draftNote: "Šis tulkojums ir vēl nepārbaudīts melnraksts; noteicošais ir teksts angļu valodā.",
      readInEnglish: "Lasīt angliski",
    },
  },
  et: {
    status: "needs_review",
    texts: {
      title: "Privaatsusteade",
      subtitle: "Kuidas {business} käsitleb seda, mida tema vestlusesse kirjutate",
      whoTitle: "Kes vastab",
      who: "{business} vastab sõnumitele tehisintellekti assistendiga – oma veebilehel, sellel lehel ja sõnumirakendustes. Assistant Workshop pakub assistenti ja töötleb teie sõnumeid {business} nimel; {business} otsustab, mida nendega tehakse.",
      whatTitle: "Mida säilitatakse",
      whatMessages: "See, mida vestlusesse kirjutate, ja assistendi vastused.",
      whatContacts: "Teie nimi, telefoninumber või e-post, kui need annate (näiteks broneeringuks või tagasihelistamiseks).",
      whatBrowser: "Juhuslik võti brauseri mälus, et vestlus jätkuks sealt, kus selle pooleli jätsite. Vestlus ei kasuta küpsiseid.",
      whatTechnical: "Tehnilised andmed, näiteks IP-aadress, mida hoitakse lühikest aega, et kaitsta vestlust kuritarvitamise eest.",
      whyTitle: "Milleks",
      why: "Et vastata teie küsimustele, võtta vastu broneeringuid ja päringuid ning anda vestlus üle {business} töötajatele, kui soovite inimest või assistent ei saa aidata.",
      sharedTitle: "Kes seda näeb",
      shared: "{business} töötajad. Vastuste kirjutamiseks töötleb vestluse teksti tehisintellekti mudeli pakkuja, mille peal assistent töötab – ainult sel eesmärgil.",
      keptTitle: "Kui kaua",
      kept: "{business} otsustab, kui kaua vestlusi säilitatakse. Võite igal ajal paluda enda oma kustutada.",
      rightsTitle: "Teie valikud",
      rights: "Võite küsida {business} käest, mida teie kohta säilitatakse, ning paluda seda parandada või kustutada: kirjutage vestlusesse või võtke ettevõttega otse ühendust. Assistent võib eksida, seega kontrollige olulisi üksikasju (hinnad, kellaajad) ettevõttelt.",
      platformNote: "See on Assistant Workshopi platvormi vaiketeade. {business} võib avaldada oma teate.",
      backToChat: "Tagasi vestlusesse",
      draftNote: "See tõlge on veel läbi vaatamata mustand; kehtib ingliskeelne tekst.",
      readInEnglish: "Loe inglise keeles",
    },
  },
  fi: {
    status: "needs_review",
    texts: {
      title: "Tietosuojailmoitus",
      subtitle: "Miten {business} käsittelee sitä, mitä kirjoitat sen chattiin",
      whoTitle: "Kuka vastaa",
      who: "{business} vastaa viesteihin tekoälyavustajalla verkkosivuillaan, tällä sivulla ja viestisovelluksissa. Assistant Workshop tarjoaa avustajan ja käsittelee viestisi yrityksen {business} puolesta; {business} päättää, mitä niille tehdään.",
      whatTitle: "Mitä säilytetään",
      whatMessages: "Mitä kirjoitat chattiin ja avustajan vastaukset.",
      whatContacts: "Nimesi, puhelinnumerosi tai sähköpostisi, jos annat ne (esimerkiksi varausta tai takaisinsoittoa varten).",
      whatBrowser: "Satunnainen avain selaimesi tallennustilassa, jotta chat jatkuu siitä, mihin jäit. Chat ei käytä evästeitä.",
      whatTechnical: "Teknisiä tietoja, kuten IP-osoitteesi, joita säilytetään lyhyen aikaa chatin suojaamiseksi väärinkäytöltä.",
      whyTitle: "Miksi",
      why: "Jotta voimme vastata kysymyksiisi, ottaa vastaan varauksia ja pyyntöjä sekä siirtää keskustelun yrityksen {business} henkilökunnalle, kun pyydät ihmistä tai avustaja ei voi auttaa.",
      sharedTitle: "Kuka sen näkee",
      shared: "Yrityksen {business} henkilökunta. Vastausten kirjoittamiseksi keskustelun tekstiä käsittelee sen tekoälymallin tarjoaja, jolla avustaja toimii – vain tähän tarkoitukseen.",
      keptTitle: "Kuinka kauan",
      kept: "{business} päättää, kuinka kauan keskusteluja säilytetään. Voit milloin tahansa pyytää poistamaan omasi.",
      rightsTitle: "Valintasi",
      rights: "Voit kysyä yritykseltä {business}, mitä se säilyttää sinusta, ja pyytää korjaamaan tai poistamaan sen: kirjoita chattiin tai ota yhteyttä yritykseen suoraan. Avustaja voi erehtyä, joten tarkista tärkeät tiedot (hinnat, ajat) yritykseltä.",
      platformNote: "Tämä on Assistant Workshop -alustan oletusilmoitus. {business} voi julkaista oman.",
      backToChat: "Takaisin chattiin",
      draftNote: "Tämä käännös on vielä tarkistamaton luonnos; englanninkielinen teksti on ratkaiseva.",
      readInEnglish: "Lue englanniksi",
    },
  },
  nb: {
    status: "needs_review",
    texts: {
      title: "Personvernerklæring",
      subtitle: "Hvordan {business} behandler det du skriver i chatten",
      whoTitle: "Hvem svarer",
      who: "{business} svarer på meldinger med en KI-assistent – på nettstedet, på denne siden og i meldingsapper. Assistant Workshop leverer assistenten og behandler meldingene dine på vegne av {business}, som bestemmer hva som gjøres med dem.",
      whatTitle: "Hva som lagres",
      whatMessages: "Det du skriver i chatten, og assistentens svar.",
      whatContacts: "Navnet ditt, telefonnummeret eller e-postadressen din, hvis du oppgir dem (for eksempel for en bestilling eller at noen skal ringe deg).",
      whatBrowser: "En tilfeldig nøkkel i nettleserens lagring, slik at chatten fortsetter der du slapp. Chatten bruker ingen informasjonskapsler.",
      whatTechnical: "Tekniske data som IP-adressen din, lagret en kort stund for å beskytte chatten mot misbruk.",
      whyTitle: "Hvorfor",
      why: "For å svare på spørsmålene dine, ta imot bestillinger og forespørsler og gi samtalen videre til de ansatte i {business} når du ber om et menneske eller assistenten ikke kan hjelpe.",
      sharedTitle: "Hvem ser det",
      shared: "De ansatte i {business}. For å skrive svar behandles teksten i samtalen av leverandøren av KI-modellen assistenten kjører på, bare til dette formålet.",
      keptTitle: "Hvor lenge",
      kept: "{business} bestemmer hvor lenge samtaler lagres. Du kan når som helst be om at din blir slettet.",
      rightsTitle: "Dine valg",
      rights: "Du kan spørre {business} hva som er lagret om deg, og be om at det rettes eller slettes: skriv i chatten eller kontakt virksomheten direkte. Assistenten kan ta feil, så sjekk viktige detaljer (priser, tider) med virksomheten.",
      platformNote: "Dette er standarderklæringen til plattformen Assistant Workshop. {business} kan publisere sin egen.",
      backToChat: "Tilbake til chatten",
      draftNote: "Denne oversettelsen er et utkast som ikke er gjennomgått ennå; den engelske teksten gjelder.",
      readInEnglish: "Les på engelsk",
    },
  },
  uk: {
    status: "needs_review",
    texts: {
      title: "Повідомлення про конфіденційність",
      subtitle: "Як {business} поводиться з тим, що ви пишете в його чаті",
      whoTitle: "Хто відповідає",
      who: "{business} відповідає на повідомлення за допомогою ШІ-помічника — на своєму сайті, на цій сторінці та в месенджерах. Assistant Workshop надає помічника й обробляє ваші повідомлення від імені {business}, який вирішує, що з ними робити.",
      whatTitle: "Що зберігається",
      whatMessages: "Те, що ви пишете в чаті, і відповіді помічника.",
      whatContacts: "Ваше ім’я, номер телефону або e-mail, якщо ви їх надаєте (наприклад, для бронювання чи зворотного дзвінка).",
      whatBrowser: "Випадковий ключ у сховищі вашого браузера, щоб чат продовжувався з того місця, де ви зупинилися. Чат не використовує cookie.",
      whatTechnical: "Технічні дані, як-от ваша IP-адреса, які зберігаються недовго, щоб захистити чат від зловживань.",
      whyTitle: "Навіщо",
      why: "Щоб відповідати на ваші запитання, приймати бронювання та заявки й передавати розмову працівникам {business}, коли ви просите людину або помічник не може допомогти.",
      sharedTitle: "Хто це бачить",
      shared: "Працівники {business}. Щоб написати відповіді, текст розмови обробляє постачальник ШІ-моделі, на якій працює помічник, — лише для цього.",
      keptTitle: "Як довго",
      kept: "{business} вирішує, як довго зберігаються розмови. Ви будь-коли можете попросити видалити вашу.",
      rightsTitle: "Ваш вибір",
      rights: "Ви можете запитати {business}, що про вас зберігається, і попросити це виправити чи видалити: напишіть у чат або зверніться до бізнесу напряму. Помічник може помилятися, тож важливі деталі (ціни, час) уточнюйте в бізнесу.",
      platformNote: "Це стандартне повідомлення платформи Assistant Workshop. {business} може опублікувати власне.",
      backToChat: "Назад до чату",
      draftNote: "Цей переклад — ще не перевірена чернетка; переважну силу має англійський текст.",
      readInEnglish: "Читати англійською",
    },
  },
};
