/** Drafts of the hosted chat's privacy notice in South and East Asian widget languages (needs_review). */

import type { PrivacyNoticeDraft } from "./noticeTypes";

export const DRAFTS_ASIA: Readonly<Record<string, PrivacyNoticeDraft>> = {
  hi: {
    status: "needs_review",
    texts: {
      title: "गोपनीयता सूचना",
      subtitle: "{business} अपनी चैट में आपके लिखे को कैसे संभालता है",
      whoTitle: "कौन जवाब देता है",
      who: "{business} संदेशों का जवाब एक AI सहायक से देता है — अपनी वेबसाइट पर, इस पेज पर और मैसेंजर में। Assistant Workshop सहायक उपलब्ध कराता है और {business} की ओर से आपके संदेशों को प्रोसेस करता है; उनके साथ क्या किया जाए, यह {business} तय करता है।",
      whatTitle: "क्या रखा जाता है",
      whatMessages: "आप चैट में जो लिखते हैं और सहायक के जवाब।",
      whatContacts: "आपका नाम, फ़ोन नंबर या ई-मेल, अगर आप दें (जैसे बुकिंग या कॉल-बैक के लिए)।",
      whatBrowser: "आपके ब्राउज़र के स्टोरेज में एक रैंडम कुंजी, ताकि चैट वहीं से जारी रहे जहाँ आपने छोड़ी थी। चैट कुकीज़ का उपयोग नहीं करती।",
      whatTechnical: "आपके IP पते जैसा तकनीकी डेटा, जो चैट को दुरुपयोग से बचाने के लिए थोड़े समय तक रखा जाता है।",
      whyTitle: "किसलिए",
      why: "आपके सवालों का जवाब देने, बुकिंग और अनुरोध लेने, और जब आप किसी व्यक्ति से बात करना चाहें या सहायक मदद न कर सके तो बातचीत {business} के स्टाफ़ को सौंपने के लिए।",
      sharedTitle: "इसे कौन देखता है",
      shared: "{business} का स्टाफ़। जवाब लिखने के लिए बातचीत का पाठ उस AI मॉडल का प्रदाता केवल इसी उद्देश्य से प्रोसेस करता है, जिस पर सहायक चलता है।",
      keptTitle: "कितने समय तक",
      kept: "बातचीत कितने समय तक रखी जाए, यह {business} तय करता है। आप कभी भी अपनी बातचीत हटाने के लिए कह सकते हैं।",
      rightsTitle: "आपके विकल्प",
      rights: "आप {business} से पूछ सकते हैं कि वह आपके बारे में क्या रखता है, और उसे सुधारने या हटाने के लिए कह सकते हैं: चैट में लिखें या सीधे व्यवसाय से संपर्क करें। सहायक गलती कर सकता है, इसलिए ज़रूरी जानकारी (कीमतें, समय) व्यवसाय से पक्की करें।",
      platformNote: "यह Assistant Workshop प्लेटफ़ॉर्म की डिफ़ॉल्ट सूचना है। {business} अपनी सूचना प्रकाशित कर सकता है।",
      backToChat: "चैट पर वापस",
      draftNote: "यह अनुवाद एक मसौदा है जिसकी अभी समीक्षा नहीं हुई है; अंग्रेज़ी पाठ ही मान्य है।",
      readInEnglish: "अंग्रेज़ी में पढ़ें",
    },
  },
  zh: {
    status: "needs_review",
    texts: {
      title: "隐私声明",
      subtitle: "{business} 如何处理您在其聊天中写下的内容",
      whoTitle: "由谁回复",
      who: "{business} 通过 AI 助手回复消息：在其网站、本页面和即时通讯应用中。Assistant Workshop 提供该助手，并代表 {business} 处理您的消息；如何处理这些消息由 {business} 决定。",
      whatTitle: "保存哪些内容",
      whatMessages: "您在聊天中写的内容以及助手的回复。",
      whatContacts: "您的姓名、电话号码或电子邮箱（如果您提供，例如用于预订或回电）。",
      whatBrowser: "浏览器存储中的一个随机密钥，使聊天能从您离开的地方继续。聊天不使用 Cookie。",
      whatTechnical: "IP 地址等技术数据，短期保存，用于防止聊天被滥用。",
      whyTitle: "用途",
      why: "用于回答您的问题、接受预订和请求，并在您要求人工服务或助手无法帮助时，将对话转交给 {business} 的员工。",
      sharedTitle: "谁能看到",
      shared: "{business} 的员工。为了撰写回复，对话文本由助手所使用的 AI 模型提供方处理，仅用于此目的。",
      keptTitle: "保存多久",
      kept: "对话保存多久由 {business} 决定。您可以随时要求删除您的对话。",
      rightsTitle: "您的选择",
      rights: "您可以询问 {business} 保存了您的哪些信息，并要求更正或删除：在聊天中留言或直接联系商家。助手可能会出错，请向商家核实重要信息（价格、时间）。",
      platformNote: "这是 Assistant Workshop 平台的默认声明。{business} 可以发布自己的声明。",
      backToChat: "返回聊天",
      draftNote: "此译文为尚未审核的草稿；以英文文本为准。",
      readInEnglish: "阅读英文版",
    },
  },
  ja: {
    status: "needs_review",
    texts: {
      title: "プライバシーに関するお知らせ",
      subtitle: "{business} がチャットに書かれた内容をどのように扱うか",
      whoTitle: "誰が返信するか",
      who: "{business} は、ウェブサイト、このページ、メッセージアプリで AI アシスタントを使ってメッセージに返信します。Assistant Workshop がアシスタントを提供し、{business} に代わってメッセージを処理します。メッセージの扱いは {business} が決定します。",
      whatTitle: "保存される情報",
      whatMessages: "チャットに書かれた内容とアシスタントの返信。",
      whatContacts: "お名前、電話番号またはメールアドレス（予約や折り返しの連絡などのためにご提供いただいた場合）。",
      whatBrowser: "中断したところからチャットを続けられるよう、ブラウザのストレージに保存されるランダムなキー。チャットは Cookie を使用しません。",
      whatTechnical: "IP アドレスなどの技術データ。チャットを不正利用から守るため、短期間だけ保存されます。",
      whyTitle: "目的",
      why: "ご質問への回答、予約やご依頼の受付、そしてスタッフとの対話をご希望の場合やアシスタントが対応できない場合に、会話を {business} のスタッフへ引き継ぐため。",
      sharedTitle: "誰が閲覧するか",
      shared: "{business} のスタッフ。返信を作成するため、会話のテキストはアシスタントが利用する AI モデルの提供者によって、その目的に限り処理されます。",
      keptTitle: "保存期間",
      kept: "会話の保存期間は {business} が決定します。いつでもご自身の会話の削除を依頼できます。",
      rightsTitle: "お客様の選択肢",
      rights: "{business} に保存されている情報を確認し、訂正や削除を依頼できます。チャットに書き込むか、事業者に直接ご連絡ください。アシスタントは誤ることがあるため、重要な詳細（料金、時間）は事業者にご確認ください。",
      platformNote: "これは Assistant Workshop プラットフォームの標準のお知らせです。{business} は独自のお知らせを公開できます。",
      backToChat: "チャットに戻る",
      draftNote: "この翻訳はまだ確認されていない草案です。英語の原文が優先します。",
      readInEnglish: "英語で読む",
    },
  },
  ko: {
    status: "needs_review",
    texts: {
      title: "개인정보 처리 안내",
      subtitle: "{business}이(가) 채팅에 작성한 내용을 처리하는 방법",
      whoTitle: "누가 답변하나요",
      who: "{business}은(는) 웹사이트, 이 페이지, 메신저에서 AI 어시스턴트로 메시지에 답변합니다. Assistant Workshop이 어시스턴트를 제공하고 {business}을(를) 대신해 메시지를 처리하며, 메시지의 처리 방식은 {business}이(가) 결정합니다.",
      whatTitle: "보관되는 정보",
      whatMessages: "채팅에 작성한 내용과 어시스턴트의 답변.",
      whatContacts: "이름, 전화번호 또는 이메일(예약이나 회신 전화 등을 위해 제공한 경우).",
      whatBrowser: "중단한 곳에서 채팅을 이어갈 수 있도록 브라우저 저장소에 보관되는 임의의 키. 채팅은 쿠키를 사용하지 않습니다.",
      whatTechnical: "IP 주소와 같은 기술 데이터. 채팅을 악용으로부터 보호하기 위해 짧은 기간 보관됩니다.",
      whyTitle: "목적",
      why: "질문에 답하고, 예약과 요청을 받으며, 상담원 연결을 요청하거나 어시스턴트가 도울 수 없을 때 대화를 {business} 직원에게 넘기기 위해서입니다.",
      sharedTitle: "누가 볼 수 있나요",
      shared: "{business}의 직원. 답변을 작성하기 위해 대화 내용은 어시스턴트가 사용하는 AI 모델 제공업체가 해당 목적으로만 처리합니다.",
      keptTitle: "보관 기간",
      kept: "대화 보관 기간은 {business}이(가) 결정합니다. 언제든지 본인의 대화 삭제를 요청할 수 있습니다.",
      rightsTitle: "선택할 수 있는 권리",
      rights: "{business}에 보관된 내 정보를 문의하고 정정이나 삭제를 요청할 수 있습니다. 채팅에 남기거나 업체에 직접 연락하세요. 어시스턴트는 실수할 수 있으니 중요한 정보(가격, 시간)는 업체에 확인하세요.",
      platformNote: "이는 Assistant Workshop 플랫폼의 기본 안내입니다. {business}은(는) 자체 안내를 게시할 수 있습니다.",
      backToChat: "채팅으로 돌아가기",
      draftNote: "이 번역은 아직 검토되지 않은 초안이며, 영어 원문이 우선합니다.",
      readInEnglish: "영어로 읽기",
    },
  },
  vi: {
    status: "needs_review",
    texts: {
      title: "Thông báo quyền riêng tư",
      subtitle: "Cách {business} xử lý những gì bạn viết trong khung chat",
      whoTitle: "Ai trả lời",
      who: "{business} trả lời tin nhắn bằng trợ lý AI — trên trang web, trên trang này và trong các ứng dụng nhắn tin. Assistant Workshop cung cấp trợ lý và xử lý tin nhắn của bạn thay mặt {business}; {business} quyết định cách sử dụng chúng.",
      whatTitle: "Những gì được lưu",
      whatMessages: "Nội dung bạn viết trong chat và câu trả lời của trợ lý.",
      whatContacts: "Tên, số điện thoại hoặc email của bạn, nếu bạn cung cấp (ví dụ để đặt chỗ hoặc gọi lại).",
      whatBrowser: "Một khóa ngẫu nhiên trong bộ nhớ trình duyệt để cuộc trò chuyện tiếp tục từ chỗ bạn dừng lại. Chat không dùng cookie.",
      whatTechnical: "Dữ liệu kỹ thuật như địa chỉ IP, được lưu trong thời gian ngắn để bảo vệ chat khỏi bị lạm dụng.",
      whyTitle: "Để làm gì",
      why: "Để trả lời câu hỏi của bạn, nhận đặt chỗ và yêu cầu, và chuyển cuộc trò chuyện cho nhân viên của {business} khi bạn muốn gặp người thật hoặc trợ lý không thể giúp.",
      sharedTitle: "Ai có thể xem",
      shared: "Nhân viên của {business}. Để viết câu trả lời, nội dung cuộc trò chuyện được nhà cung cấp mô hình AI mà trợ lý sử dụng xử lý, chỉ cho mục đích đó.",
      keptTitle: "Lưu bao lâu",
      kept: "{business} quyết định lưu các cuộc trò chuyện trong bao lâu. Bạn có thể yêu cầu xóa cuộc trò chuyện của mình bất cứ lúc nào.",
      rightsTitle: "Lựa chọn của bạn",
      rights: "Bạn có thể hỏi {business} đang lưu gì về bạn và yêu cầu sửa hoặc xóa: hãy viết trong chat hoặc liên hệ trực tiếp với doanh nghiệp. Trợ lý có thể nhầm lẫn, vì vậy hãy xác nhận các chi tiết quan trọng (giá, giờ) với doanh nghiệp.",
      platformNote: "Đây là thông báo mặc định của nền tảng Assistant Workshop. {business} có thể đăng thông báo riêng.",
      backToChat: "Quay lại chat",
      draftNote: "Bản dịch này là bản nháp chưa được kiểm tra; văn bản tiếng Anh có giá trị ưu tiên.",
      readInEnglish: "Đọc bằng tiếng Anh",
    },
  },
};
