/** Drafts of the hosted chat's privacy notice in western European widget languages (needs_review). */

import type { PrivacyNoticeDraft } from "./noticeTypes";

export const DRAFTS_EUROPE_WEST: Readonly<Record<string, PrivacyNoticeDraft>> = {
  de: {
    status: "needs_review",
    texts: {
      title: "Datenschutzhinweis",
      subtitle: "Wie {business} mit dem umgeht, was Sie in den Chat schreiben",
      whoTitle: "Wer antwortet",
      who: "{business} beantwortet Nachrichten mit einem KI-Assistenten – auf der Website, auf dieser Seite und in Messengern. Assistant Workshop stellt den Assistenten bereit und verarbeitet Ihre Nachrichten im Auftrag von {business}; {business} entscheidet, was mit ihnen geschieht.",
      whatTitle: "Was gespeichert wird",
      whatMessages: "Was Sie in den Chat schreiben, und die Antworten des Assistenten.",
      whatContacts: "Ihr Name, Ihre Telefonnummer oder E-Mail-Adresse, wenn Sie sie angeben (zum Beispiel für eine Buchung oder einen Rückruf).",
      whatBrowser: "Ein zufälliger Schlüssel im Speicher Ihres Browsers, damit der Chat dort weitergeht, wo Sie aufgehört haben. Der Chat setzt keine Cookies.",
      whatTechnical: "Technische Daten wie Ihre IP-Adresse, für kurze Zeit gespeichert, um den Chat vor Missbrauch zu schützen.",
      whyTitle: "Wozu",
      why: "Um Ihre Fragen zu beantworten, Buchungen und Anfragen aufzunehmen und das Gespräch an die Mitarbeitenden von {business} weiterzugeben, wenn Sie eine Person sprechen möchten oder der Assistent nicht helfen kann.",
      sharedTitle: "Wer es sieht",
      shared: "Die Mitarbeitenden von {business}. Um Antworten zu schreiben, wird der Text des Gesprächs vom Anbieter des KI-Modells verarbeitet, auf dem der Assistent läuft – nur zu diesem Zweck.",
      keptTitle: "Wie lange",
      kept: "{business} entscheidet, wie lange Gespräche gespeichert werden. Sie können jederzeit verlangen, dass Ihres gelöscht wird.",
      rightsTitle: "Ihre Möglichkeiten",
      rights: "Sie können {business} fragen, was über Sie gespeichert ist, und die Berichtigung oder Löschung verlangen: Schreiben Sie in den Chat oder wenden Sie sich direkt an das Unternehmen. Der Assistent kann sich irren – prüfen Sie wichtige Angaben (Preise, Zeiten) beim Unternehmen.",
      platformNote: "Dies ist der Standardhinweis der Plattform Assistant Workshop. {business} kann einen eigenen veröffentlichen.",
      backToChat: "Zurück zum Chat",
      draftNote: "Diese Übersetzung ist ein noch nicht geprüfter Entwurf; maßgeblich ist der englische Text.",
      readInEnglish: "Auf Englisch lesen",
    },
  },
  fr: {
    status: "needs_review",
    texts: {
      title: "Avis de confidentialité",
      subtitle: "Comment {business} traite ce que vous écrivez dans son chat",
      whoTitle: "Qui répond",
      who: "{business} répond aux messages avec un assistant IA, sur son site, sur cette page et dans les messageries. Assistant Workshop fournit l’assistant et traite vos messages pour le compte de {business}, qui décide de ce qui en est fait.",
      whatTitle: "Ce qui est conservé",
      whatMessages: "Ce que vous écrivez dans le chat et les réponses de l’assistant.",
      whatContacts: "Votre nom, votre numéro de téléphone ou votre e-mail, si vous les donnez (par exemple pour une réservation ou un rappel).",
      whatBrowser: "Une clé aléatoire dans le stockage de votre navigateur, pour que le chat reprenne là où vous l’avez laissé. Le chat ne dépose aucun cookie.",
      whatTechnical: "Des données techniques comme votre adresse IP, conservées peu de temps pour protéger le chat contre les abus.",
      whyTitle: "Pourquoi",
      why: "Pour répondre à vos questions, prendre les réservations et les demandes, et transmettre la conversation à l’équipe de {business} lorsque vous demandez une personne ou que l’assistant ne peut pas aider.",
      sharedTitle: "Qui y a accès",
      shared: "L’équipe de {business}. Pour rédiger les réponses, le texte de la conversation est traité par le fournisseur du modèle d’IA sur lequel fonctionne l’assistant, uniquement à cette fin.",
      keptTitle: "Combien de temps",
      kept: "{business} décide de la durée de conservation des conversations. Vous pouvez à tout moment lui demander de supprimer la vôtre.",
      rightsTitle: "Vos choix",
      rights: "Vous pouvez demander à {business} ce qu’il conserve sur vous, et le faire corriger ou supprimer : écrivez dans le chat ou contactez directement l’établissement. L’assistant peut se tromper : vérifiez les détails importants (prix, horaires) auprès de l’établissement.",
      platformNote: "Ceci est l’avis par défaut de la plateforme Assistant Workshop. {business} peut publier le sien.",
      backToChat: "Retour au chat",
      draftNote: "Cette traduction est un projet qui n’a pas encore été relu ; le texte anglais fait foi.",
      readInEnglish: "Lire en anglais",
    },
  },
  es: {
    status: "needs_review",
    texts: {
      title: "Aviso de privacidad",
      subtitle: "Cómo trata {business} lo que escribes en su chat",
      whoTitle: "Quién responde",
      who: "{business} responde a los mensajes con un asistente de IA, en su sitio web, en esta página y en mensajería. Assistant Workshop proporciona el asistente y trata tus mensajes por cuenta de {business}, que decide qué se hace con ellos.",
      whatTitle: "Qué se guarda",
      whatMessages: "Lo que escribes en el chat y las respuestas del asistente.",
      whatContacts: "Tu nombre, tu teléfono o tu correo electrónico, si los das (por ejemplo, para una reserva o para que te llamen).",
      whatBrowser: "Una clave aleatoria en el almacenamiento de tu navegador, para que el chat siga donde lo dejaste. El chat no usa cookies.",
      whatTechnical: "Datos técnicos como tu dirección IP, guardados poco tiempo para proteger el chat de abusos.",
      whyTitle: "Para qué",
      why: "Para responder a tus preguntas, tomar reservas y solicitudes, y pasar la conversación al personal de {business} cuando pides hablar con una persona o el asistente no puede ayudar.",
      sharedTitle: "Quién lo ve",
      shared: "El personal de {business}. Para redactar las respuestas, el texto de la conversación lo procesa el proveedor del modelo de IA en el que funciona el asistente, solo con ese fin.",
      keptTitle: "Cuánto tiempo",
      kept: "{business} decide cuánto tiempo se guardan las conversaciones. Puedes pedirle en cualquier momento que borre la tuya.",
      rightsTitle: "Tus opciones",
      rights: "Puedes preguntar a {business} qué guarda sobre ti y pedir que lo corrija o lo borre: escribe en el chat o contacta directamente con el negocio. El asistente puede equivocarse, así que confirma los detalles importantes (precios, horarios) con el negocio.",
      platformNote: "Este es el aviso predeterminado de la plataforma Assistant Workshop. {business} puede publicar el suyo.",
      backToChat: "Volver al chat",
      draftNote: "Esta traducción es un borrador aún sin revisar; prevalece el texto en inglés.",
      readInEnglish: "Leer en inglés",
    },
  },
  it: {
    status: "needs_review",
    texts: {
      title: "Informativa sulla privacy",
      subtitle: "Come {business} tratta ciò che scrivi nella sua chat",
      whoTitle: "Chi risponde",
      who: "{business} risponde ai messaggi con un assistente IA, sul suo sito, in questa pagina e nelle app di messaggistica. Assistant Workshop fornisce l’assistente e tratta i tuoi messaggi per conto di {business}, che decide cosa farne.",
      whatTitle: "Cosa viene conservato",
      whatMessages: "Ciò che scrivi nella chat e le risposte dell’assistente.",
      whatContacts: "Il tuo nome, numero di telefono o e-mail, se li fornisci (ad esempio per una prenotazione o per essere richiamato).",
      whatBrowser: "Una chiave casuale nella memoria del tuo browser, perché la chat riprenda da dove l’hai lasciata. La chat non usa cookie.",
      whatTechnical: "Dati tecnici come il tuo indirizzo IP, conservati per poco tempo per proteggere la chat dagli abusi.",
      whyTitle: "Perché",
      why: "Per rispondere alle tue domande, raccogliere prenotazioni e richieste e passare la conversazione al personale di {business} quando chiedi di parlare con una persona o l’assistente non può aiutarti.",
      sharedTitle: "Chi lo vede",
      shared: "Il personale di {business}. Per scrivere le risposte, il testo della conversazione è trattato dal fornitore del modello di IA su cui funziona l’assistente, solo a questo scopo.",
      keptTitle: "Per quanto tempo",
      kept: "{business} decide per quanto tempo conservare le conversazioni. Puoi chiedergli in qualsiasi momento di cancellare la tua.",
      rightsTitle: "Le tue scelte",
      rights: "Puoi chiedere a {business} cosa conserva su di te e chiederne la correzione o la cancellazione: scrivi nella chat o contatta direttamente l’attività. L’assistente può sbagliare: verifica i dettagli importanti (prezzi, orari) con l’attività.",
      platformNote: "Questa è l’informativa predefinita della piattaforma Assistant Workshop. {business} può pubblicarne una propria.",
      backToChat: "Torna alla chat",
      draftNote: "Questa traduzione è una bozza non ancora revisionata; fa fede il testo inglese.",
      readInEnglish: "Leggi in inglese",
    },
  },
  pt: {
    status: "needs_review",
    texts: {
      title: "Aviso de privacidade",
      subtitle: "Como {business} trata o que escreve no chat",
      whoTitle: "Quem responde",
      who: "{business} responde às mensagens com um assistente de IA, no site, nesta página e em aplicações de mensagens. A Assistant Workshop fornece o assistente e trata as suas mensagens por conta de {business}, que decide o que é feito com elas.",
      whatTitle: "O que é guardado",
      whatMessages: "O que escreve no chat e as respostas do assistente.",
      whatContacts: "O seu nome, telefone ou e-mail, se os indicar (por exemplo, para uma reserva ou para lhe ligarem).",
      whatBrowser: "Uma chave aleatória no armazenamento do seu navegador, para que o chat continue onde parou. O chat não usa cookies.",
      whatTechnical: "Dados técnicos como o seu endereço IP, guardados por pouco tempo para proteger o chat contra abusos.",
      whyTitle: "Para quê",
      why: "Para responder às suas perguntas, receber reservas e pedidos e passar a conversa à equipa de {business} quando pede para falar com uma pessoa ou o assistente não consegue ajudar.",
      sharedTitle: "Quem vê",
      shared: "A equipa de {business}. Para escrever as respostas, o texto da conversa é tratado pelo fornecedor do modelo de IA em que o assistente funciona, apenas para esse fim.",
      keptTitle: "Durante quanto tempo",
      kept: "{business} decide durante quanto tempo as conversas são guardadas. Pode pedir a qualquer momento que apague a sua.",
      rightsTitle: "As suas opções",
      rights: "Pode perguntar a {business} o que guarda sobre si e pedir que o corrija ou apague: escreva no chat ou contacte diretamente o negócio. O assistente pode enganar-se, por isso confirme os detalhes importantes (preços, horários) com o negócio.",
      platformNote: "Este é o aviso predefinido da plataforma Assistant Workshop. {business} pode publicar o seu.",
      backToChat: "Voltar ao chat",
      draftNote: "Esta tradução é um rascunho ainda não revisto; prevalece o texto em inglês.",
      readInEnglish: "Ler em inglês",
    },
  },
  pl: {
    status: "needs_review",
    texts: {
      title: "Informacja o prywatności",
      subtitle: "Jak {business} postępuje z tym, co piszesz na czacie",
      whoTitle: "Kto odpowiada",
      who: "{business} odpowiada na wiadomości za pomocą asystenta AI – na swojej stronie, na tej stronie i w komunikatorach. Assistant Workshop dostarcza asystenta i przetwarza Twoje wiadomości w imieniu {business}, który decyduje, co się z nimi dzieje.",
      whatTitle: "Co jest przechowywane",
      whatMessages: "To, co piszesz na czacie, i odpowiedzi asystenta.",
      whatContacts: "Twoje imię, numer telefonu lub e-mail, jeśli je podasz (na przykład do rezerwacji lub oddzwonienia).",
      whatBrowser: "Losowy klucz w pamięci przeglądarki, aby czat był kontynuowany tam, gdzie go przerwałeś. Czat nie używa plików cookie.",
      whatTechnical: "Dane techniczne, takie jak adres IP, przechowywane krótko, aby chronić czat przed nadużyciami.",
      whyTitle: "Po co",
      why: "Aby odpowiadać na pytania, przyjmować rezerwacje i zgłoszenia oraz przekazywać rozmowę pracownikom {business}, gdy poprosisz o kontakt z człowiekiem lub asystent nie może pomóc.",
      sharedTitle: "Kto to widzi",
      shared: "Pracownicy {business}. Aby napisać odpowiedzi, tekst rozmowy przetwarza dostawca modelu AI, na którym działa asystent – wyłącznie w tym celu.",
      keptTitle: "Jak długo",
      kept: "{business} decyduje, jak długo przechowywane są rozmowy. W każdej chwili możesz poprosić o usunięcie swojej.",
      rightsTitle: "Twoje możliwości",
      rights: "Możesz zapytać {business}, co o Tobie przechowuje, i poprosić o poprawienie lub usunięcie tych danych: napisz na czacie lub skontaktuj się bezpośrednio z firmą. Asystent może się mylić, dlatego ważne szczegóły (ceny, godziny) potwierdzaj w firmie.",
      platformNote: "To domyślna informacja platformy Assistant Workshop. {business} może opublikować własną.",
      backToChat: "Wróć do czatu",
      draftNote: "To tłumaczenie jest wersją roboczą, jeszcze nie sprawdzoną; rozstrzyga tekst angielski.",
      readInEnglish: "Czytaj po angielsku",
    },
  },
};
