/** Drafts of the hosted chat's privacy notice in Caucasian, Turkic and Central Asian widget languages (needs_review). */

import type { PrivacyNoticeDraft } from "./noticeTypes";

export const DRAFTS_CAUCASUS_TURKIC: Readonly<Record<string, PrivacyNoticeDraft>> = {
  hy: {
    status: "needs_review",
    texts: {
      title: "Գաղտնիության ծանուցում",
      subtitle: "Ինչպես է {business}-ը վարվում այն ամենի հետ, ինչ գրում եք իր չատում",
      whoTitle: "Ով է պատասխանում",
      who: "{business}-ը հաղորդագրություններին պատասխանում է արհեստական բանականության օգնականով՝ իր կայքում, այս էջում և մեսենջերներում։ Assistant Workshop-ը տրամադրում է օգնականը և մշակում է ձեր հաղորդագրությունները {business}-ի անունից, որը որոշում է, թե ինչ անել դրանց հետ։",
      whatTitle: "Ինչ է պահվում",
      whatMessages: "Այն, ինչ գրում եք չատում, և օգնականի պատասխանները։",
      whatContacts: "Ձեր անունը, հեռախոսահամարը կամ էլ. փոստը, եթե տրամադրում եք (օրինակ՝ ամրագրման կամ հետզանգի համար)։",
      whatBrowser: "Պատահական բանալի ձեր դիտարկչի պահոցում, որպեսզի չատը շարունակվի այնտեղից, որտեղ թողել եք։ Չատը քուքիներ չի օգտագործում։",
      whatTechnical: "Տեխնիկական տվյալներ, օրինակ՝ ձեր IP հասցեն, որոնք կարճ ժամանակ պահվում են չատը չարաշահումից պաշտպանելու համար։",
      whyTitle: "Ինչի համար",
      why: "Ձեր հարցերին պատասխանելու, ամրագրումներ և հայտեր ընդունելու և զրույցը {business}-ի աշխատակիցներին փոխանցելու համար, երբ մարդ եք խնդրում կամ օգնականը չի կարող օգնել։",
      sharedTitle: "Ով է տեսնում",
      shared: "{business}-ի աշխատակիցները։ Պատասխաններ գրելու համար զրույցի տեքստը մշակում է այն ԱԲ մոդելի մատակարարը, որով աշխատում է օգնականը, միայն այդ նպատակով։",
      keptTitle: "Որքան ժամանակ",
      kept: "{business}-ը որոշում է, թե որքան ժամանակ են պահվում զրույցները։ Կարող եք ցանկացած պահի խնդրել ջնջել ձերը։",
      rightsTitle: "Ձեր ընտրությունը",
      rights: "Կարող եք հարցնել {business}-ին, թե ինչ է պահում ձեր մասին, և խնդրել ուղղել կամ ջնջել այն՝ գրեք չատում կամ ուղղակիորեն կապվեք բիզնեսի հետ։ Օգնականը կարող է սխալվել, ուստի կարևոր մանրամասները (գներ, ժամեր) ճշտեք բիզնեսի հետ։",
      platformNote: "Սա Assistant Workshop հարթակի լռելյայն ծանուցումն է։ {business}-ը կարող է հրապարակել իրենը։",
      backToChat: "Վերադառնալ չատ",
      draftNote: "Այս թարգմանությունը դեռ չստուգված նախագիծ է․ գերակա է անգլերեն տեքստը։",
      readInEnglish: "Կարդալ անգլերենով",
    },
  },
  az: {
    status: "needs_review",
    texts: {
      title: "Məxfilik bildirişi",
      subtitle: "{business} söhbətində yazdıqlarınızla necə davranır",
      whoTitle: "Kim cavab verir",
      who: "{business} mesajlara süni intellekt köməkçisi ilə cavab verir – öz saytında, bu səhifədə və messencerlərdə. Assistant Workshop köməkçini təqdim edir və mesajlarınızı {business} adından emal edir; onlarla nə ediləcəyinə {business} qərar verir.",
      whatTitle: "Nə saxlanılır",
      whatMessages: "Söhbətdə yazdıqlarınız və köməkçinin cavabları.",
      whatContacts: "Adınız, telefon nömrəniz və ya e-poçtunuz, əgər onları bildirsəniz (məsələn, rezervasiya və ya geri zəng üçün).",
      whatBrowser: "Brauzerinizin yaddaşında təsadüfi açar ki, söhbət dayandığınız yerdən davam etsin. Söhbət kukilərdən istifadə etmir.",
      whatTechnical: "IP ünvanınız kimi texniki məlumatlar, söhbəti sui-istifadədən qorumaq üçün qısa müddət saxlanılır.",
      whyTitle: "Nə üçün",
      why: "Suallarınıza cavab vermək, rezervasiya və sorğuları qəbul etmək, insanla danışmaq istədikdə və ya köməkçi kömək edə bilmədikdə söhbəti {business} əməkdaşlarına ötürmək üçün.",
      sharedTitle: "Kim görür",
      shared: "{business} əməkdaşları. Cavablar yazmaq üçün söhbətin mətni köməkçinin işlədiyi süni intellekt modelinin təchizatçısı tərəfindən yalnız bu məqsədlə emal olunur.",
      keptTitle: "Nə qədər",
      kept: "Söhbətlərin nə qədər saxlanılacağına {business} qərar verir. İstənilən vaxt öz söhbətinizin silinməsini xahiş edə bilərsiniz.",
      rightsTitle: "Seçimləriniz",
      rights: "{business}-dən sizin haqqınızda nə saxladığını soruşa, onu düzəltməyi və ya silməyi xahiş edə bilərsiniz: söhbətdə yazın və ya birbaşa müəssisə ilə əlaqə saxlayın. Köməkçi səhv edə bilər, ona görə vacib detalları (qiymətlər, vaxtlar) müəssisədən dəqiqləşdirin.",
      platformNote: "Bu, Assistant Workshop platformasının standart bildirişidir. {business} öz bildirişini dərc edə bilər.",
      backToChat: "Söhbətə qayıt",
      draftNote: "Bu tərcümə hələ yoxlanılmamış qaralamadır; əsas mətn ingiliscə olandır.",
      readInEnglish: "İngiliscə oxu",
    },
  },
  tr: {
    status: "needs_review",
    texts: {
      title: "Gizlilik bildirimi",
      subtitle: "{business}, sohbetine yazdıklarınızı nasıl işler",
      whoTitle: "Kim yanıtlıyor",
      who: "{business}, mesajları web sitesinde, bu sayfada ve mesajlaşma uygulamalarında bir yapay zekâ asistanıyla yanıtlar. Assistant Workshop asistanı sağlar ve mesajlarınızı {business} adına işler; bunlarla ne yapılacağına {business} karar verir.",
      whatTitle: "Neler saklanır",
      whatMessages: "Sohbete yazdıklarınız ve asistanın yanıtları.",
      whatContacts: "Verirseniz adınız, telefon numaranız veya e-postanız (örneğin bir rezervasyon ya da geri arama için).",
      whatBrowser: "Sohbetin kaldığınız yerden devam etmesi için tarayıcınızın deposunda rastgele bir anahtar. Sohbet çerez kullanmaz.",
      whatTechnical: "Sohbeti kötüye kullanıma karşı korumak için kısa süre saklanan IP adresiniz gibi teknik veriler.",
      whyTitle: "Neden",
      why: "Sorularınızı yanıtlamak, rezervasyon ve talepleri almak, bir insanla görüşmek istediğinizde veya asistan yardımcı olamadığında sohbeti {business} çalışanlarına aktarmak için.",
      sharedTitle: "Kim görür",
      shared: "{business} çalışanları. Yanıtları yazmak için sohbetin metni, asistanın çalıştığı yapay zekâ modelinin sağlayıcısı tarafından yalnızca bu amaçla işlenir.",
      keptTitle: "Ne kadar süre",
      kept: "Sohbetlerin ne kadar saklanacağına {business} karar verir. İstediğiniz zaman sizinkinin silinmesini isteyebilirsiniz.",
      rightsTitle: "Seçimleriniz",
      rights: "{business}'ten hakkınızda neler sakladığını sorabilir, düzeltilmesini veya silinmesini isteyebilirsiniz: sohbete yazın ya da işletmeyle doğrudan iletişime geçin. Asistan hata yapabilir; önemli ayrıntıları (fiyatlar, saatler) işletmeyle teyit edin.",
      platformNote: "Bu, Assistant Workshop platformunun varsayılan bildirimidir. {business} kendi bildirimini yayımlayabilir.",
      backToChat: "Sohbete dön",
      draftNote: "Bu çeviri henüz gözden geçirilmemiş bir taslaktır; esas olan İngilizce metindir.",
      readInEnglish: "İngilizce oku",
    },
  },
  kk: {
    status: "needs_review",
    texts: {
      title: "Құпиялылық туралы хабарлама",
      subtitle: "{business} чатына жазғаныңызды қалай өңдейді",
      whoTitle: "Кім жауап береді",
      who: "{business} хабарламаларға жасанды интеллект көмекшісі арқылы жауап береді — өз сайтында, осы бетте және мессенджерлерде. Assistant Workshop көмекшіні ұсынады және хабарламаларыңызды {business} атынан өңдейді; олармен не істеу керегін {business} шешеді.",
      whatTitle: "Не сақталады",
      whatMessages: "Чатқа жазғаныңыз және көмекшінің жауаптары.",
      whatContacts: "Атыңыз, телефон нөміріңіз немесе e-mail, егер оларды берсеңіз (мысалы, брондау немесе кері қоңырау үшін).",
      whatBrowser: "Чат тоқтаған жерінен жалғасуы үшін браузеріңіздің жадындағы кездейсоқ кілт. Чат cookie файлдарын қолданбайды.",
      whatTechnical: "IP мекенжайыңыз сияқты техникалық деректер, чатты теріс пайдаланудан қорғау үшін қысқа уақыт сақталады.",
      whyTitle: "Не үшін",
      why: "Сұрақтарыңызға жауап беру, брондаулар мен өтінімдерді қабылдау және адаммен сөйлескіңіз келсе немесе көмекші көмектесе алмаса, әңгімені {business} қызметкерлеріне беру үшін.",
      sharedTitle: "Кім көреді",
      shared: "{business} қызметкерлері. Жауап жазу үшін әңгіме мәтінін көмекші жұмыс істейтін ЖИ моделінің жеткізушісі тек осы мақсатта өңдейді.",
      keptTitle: "Қанша уақыт",
      kept: "Әңгімелердің қанша уақыт сақталатынын {business} шешеді. Кез келген уақытта өзіңіздікін жоюды сұрай аласыз.",
      rightsTitle: "Сіздің таңдауыңыз",
      rights: "{business}-тен сіз туралы не сақталатынын сұрап, оны түзетуді немесе жоюды өтіне аласыз: чатқа жазыңыз немесе бизнеспен тікелей байланысыңыз. Көмекші қателесуі мүмкін, сондықтан маңызды мәліметтерді (бағалар, уақыт) бизнестен нақтылаңыз.",
      platformNote: "Бұл — Assistant Workshop платформасының әдепкі хабарламасы. {business} өз хабарламасын жариялай алады.",
      backToChat: "Чатқа оралу",
      draftNote: "Бұл аударма — әлі тексерілмеген жоба; ағылшын мәтіні басым болады.",
      readInEnglish: "Ағылшынша оқу",
    },
  },
  uz: {
    status: "needs_review",
    texts: {
      title: "Maxfiylik bildirishnomasi",
      subtitle: "{business} chatiga yozganlaringiz bilan qanday ishlaydi",
      whoTitle: "Kim javob beradi",
      who: "{business} xabarlarga sun’iy intellekt yordamchisi orqali javob beradi — o‘z saytida, ushbu sahifada va messenjerlarda. Assistant Workshop yordamchini taqdim etadi va xabarlaringizni {business} nomidan qayta ishlaydi; ular bilan nima qilinishini {business} hal qiladi.",
      whatTitle: "Nima saqlanadi",
      whatMessages: "Chatga yozganlaringiz va yordamchining javoblari.",
      whatContacts: "Ismingiz, telefon raqamingiz yoki e-pochtangiz, agar ularni bersangiz (masalan, bron qilish yoki qayta qo‘ng‘iroq uchun).",
      whatBrowser: "Chat to‘xtagan joyingizdan davom etishi uchun brauzeringiz xotirasidagi tasodifiy kalit. Chat cookie-fayllardan foydalanmaydi.",
      whatTechnical: "IP manzilingiz kabi texnik ma’lumotlar, chatni suiiste’moldan himoya qilish uchun qisqa muddat saqlanadi.",
      whyTitle: "Nima uchun",
      why: "Savollaringizga javob berish, bronlar va so‘rovlarni qabul qilish hamda inson bilan gaplashmoqchi bo‘lsangiz yoki yordamchi yordam bera olmasa, suhbatni {business} xodimlariga uzatish uchun.",
      sharedTitle: "Kim ko‘radi",
      shared: "{business} xodimlari. Javob yozish uchun suhbat matnini yordamchi ishlaydigan SI modeli yetkazib beruvchisi faqat shu maqsadda qayta ishlaydi.",
      keptTitle: "Qancha vaqt",
      kept: "Suhbatlar qancha saqlanishini {business} hal qiladi. Istalgan vaqtda o‘zingiznikini o‘chirishni so‘rashingiz mumkin.",
      rightsTitle: "Sizning tanlovingiz",
      rights: "{business}dan siz haqingizda nima saqlanayotganini so‘rashingiz va uni tuzatish yoki o‘chirishni so‘rashingiz mumkin: chatga yozing yoki biznes bilan bevosita bog‘laning. Yordamchi xato qilishi mumkin, shuning uchun muhim tafsilotlarni (narxlar, vaqt) biznesdan aniqlang.",
      platformNote: "Bu Assistant Workshop platformasining standart bildirishnomasi. {business} o‘zinikini e’lon qilishi mumkin.",
      backToChat: "Chatga qaytish",
      draftNote: "Bu tarjima hali tekshirilmagan qoralama; ustun matn — ingliz tilidagi matn.",
      readInEnglish: "Inglizcha o‘qish",
    },
  },
};
