/** Booking page texts: Portuguese, Polish, Turkish, Russian, Ukrainian (see texts.ts). */

import type { BookingPageTexts } from "./texts";

export const TEXTS_MIDDLE: Readonly<Record<string, BookingPageTexts>> = {
  pt: {
    pageTitle: "Sua reserva",
    statusPending: "Aguardando confirmação",
    statusConfirmed: "Confirmada",
    statusCancelled: "Cancelada",
    statusCompleted: "Concluída",
    statusNoShow: "Não compareceu",
    when: "Quando",
    arrival: "Chegada",
    departure: "Saída",
    guests: "Pessoas",
    service: "Serviço",
    address: "Endereço",
    openMap: "Abrir no mapa",
    phone: "Telefone",
    policy: "Política de cancelamento",
    addToCalendar: "Adicionar ao calendário",
    writeToUs: "Fale conosco",
    chat: "Chat",
    call: "Ligar",
    change: "Mudar horário",
    cancel: "Cancelar reserva",
    cancelTitle: "Cancelar esta reserva?",
    cancelText: "{business} será avisado na hora. Para reservar de novo, é só nos escrever.",
    keep: "Manter reserva",
    confirmCancel: "Sim, cancelar",
    cancelling: "Cancelando…",
    cancelledNotice: "Sua reserva foi cancelada. Avisamos {business}.",
    newTime: "Escolha um novo horário",
    date: "Data",
    freeTimes: "Horários livres",
    noTimes: "Não há horários livres neste dia. Tente outra data.",
    closedDay: "Fechado neste dia. Tente outra data.",
    stayFree: "Disponível nas suas datas.",
    stayTaken: "Indisponível nestas datas. Tente outra data.",
    loadingTimes: "Procurando horários livres…",
    moveTo: "Mudar para {when}",
    moving: "Mudando…",
    close: "Fechar",
    movedNotice: "Pronto! Sua reserva foi remarcada. Esta página tem um novo endereço, e seu chat tem o novo link.",
    overNotice: "Esta visita já terminou. Obrigado pela visita!",
    startedNotice: "Sua visita já começou. Para qualquer mudança, fale conosco.",
    errorTitle: "Não é possível abrir esta reserva",
    linkInvalid: "Este link não funciona. Verifique se o abriu por inteiro.",
    linkExpired: "Este link expirou.",
    bookingChanged: "Esta reserva mudou depois do envio do link. Abra a confirmação mais recente no seu chat.",
    notActive: "Esta reserva não pode mais ser alterada.",
    alreadyStarted: "Esta reserva já começou e não pode mais ser alterada aqui.",
    taken: "Esse horário acabou de ser ocupado. Escolha outro.",
    closedTime: "Nesse horário está fechado. Escolha outro.",
    tooMany: "Tentativas demais. Aguarde um minuto e tente de novo.",
    generic: "Algo deu errado. Tente novamente em instantes.",
  },
  pl: {
    pageTitle: "Twoja rezerwacja",
    statusPending: "Czeka na potwierdzenie",
    statusConfirmed: "Potwierdzona",
    statusCancelled: "Odwołana",
    statusCompleted: "Zakończona",
    statusNoShow: "Nieobecność",
    when: "Kiedy",
    arrival: "Przyjazd",
    departure: "Wyjazd",
    guests: "Liczba gości",
    service: "Usługa",
    address: "Adres",
    openMap: "Otwórz w mapach",
    phone: "Telefon",
    policy: "Zasady odwołania",
    addToCalendar: "Dodaj do kalendarza",
    writeToUs: "Napisz do nas",
    chat: "Czat",
    call: "Zadzwoń",
    change: "Zmień termin",
    cancel: "Odwołaj rezerwację",
    cancelTitle: "Odwołać tę rezerwację?",
    cancelText: "{business} dowie się o tym od razu. Aby zarezerwować ponownie, napisz do nas.",
    keep: "Zachowaj rezerwację",
    confirmCancel: "Tak, odwołaj",
    cancelling: "Odwoływanie…",
    cancelledNotice: "Twoja rezerwacja została odwołana. Powiadomiliśmy: {business}.",
    newTime: "Wybierz nowy termin",
    date: "Data",
    freeTimes: "Wolne godziny",
    noTimes: "Brak wolnych godzin tego dnia. Wybierz inną datę.",
    closedDay: "Tego dnia zamknięte. Wybierz inną datę.",
    stayFree: "Wolne w Twoich terminach.",
    stayTaken: "Zajęte w tych terminach. Wybierz inną datę.",
    loadingTimes: "Szukamy wolnych godzin…",
    moveTo: "Przenieś: {when}",
    moving: "Przenoszenie…",
    close: "Zamknij",
    movedNotice: "Gotowe! Twoja rezerwacja została przeniesiona. Ta strona ma nowy adres, a Twój czat — nowy link.",
    overNotice: "Ta wizyta już się odbyła. Dziękujemy!",
    startedNotice: "Twoja wizyta już się zaczęła. Aby coś zmienić, napisz do nas.",
    errorTitle: "Nie można otworzyć tej rezerwacji",
    linkInvalid: "Ten link nie działa. Sprawdź, czy otwarto go w całości.",
    linkExpired: "Ten link wygasł.",
    bookingChanged: "Rezerwacja zmieniła się po wysłaniu linku. Otwórz najnowsze potwierdzenie w czacie.",
    notActive: "Tej rezerwacji nie można już zmienić.",
    alreadyStarted: "Ta rezerwacja już się zaczęła i nie można jej tu zmienić.",
    taken: "Ten termin właśnie został zajęty. Wybierz inny.",
    closedTime: "O tej godzinie jest zamknięte. Wybierz inną.",
    tooMany: "Zbyt wiele prób. Odczekaj minutę i spróbuj ponownie.",
    generic: "Coś poszło nie tak. Spróbuj ponownie za chwilę.",
  },
  tr: {
    pageTitle: "Rezervasyonunuz",
    statusPending: "Onay bekliyor",
    statusConfirmed: "Onaylandı",
    statusCancelled: "İptal edildi",
    statusCompleted: "Tamamlandı",
    statusNoShow: "Gelinmedi",
    when: "Ne zaman",
    arrival: "Giriş",
    departure: "Çıkış",
    guests: "Kişi sayısı",
    service: "Hizmet",
    address: "Adres",
    openMap: "Haritada aç",
    phone: "Telefon",
    policy: "İptal koşulları",
    addToCalendar: "Takvime ekle",
    writeToUs: "Bize yazın",
    chat: "Sohbet",
    call: "Ara",
    change: "Saati değiştir",
    cancel: "Rezervasyonu iptal et",
    cancelTitle: "Bu rezervasyon iptal edilsin mi?",
    cancelText: "{business} hemen haberdar edilecek. Yeniden rezervasyon için bize yazmanız yeterli.",
    keep: "Rezervasyonu koru",
    confirmCancel: "Evet, iptal et",
    cancelling: "İptal ediliyor…",
    cancelledNotice: "Rezervasyonunuz iptal edildi. {business} bilgilendirildi.",
    newTime: "Yeni bir saat seçin",
    date: "Tarih",
    freeTimes: "Boş saatler",
    noTimes: "Bu günde boş saat yok. Başka bir tarih deneyin.",
    closedDay: "Bu gün kapalı. Başka bir tarih deneyin.",
    stayFree: "Tarihleriniz için müsait.",
    stayTaken: "Bu tarihler için müsait değil. Başka bir tarih deneyin.",
    loadingTimes: "Boş saatler aranıyor…",
    moveTo: "Taşı: {when}",
    moving: "Taşınıyor…",
    close: "Kapat",
    movedNotice: "Tamam! Rezervasyonunuz taşındı. Bu sayfanın yeni bir adresi var; yeni bağlantı sohbetinizde de var.",
    overNotice: "Bu ziyaret sona erdi. Geldiğiniz için teşekkürler!",
    startedNotice: "Ziyaretiniz başladı. Bir şey değiştirmek için bize yazın.",
    errorTitle: "Bu rezervasyon açılamıyor",
    linkInvalid: "Bu bağlantı çalışmıyor. Bağlantının tamamını açtığınızdan emin olun.",
    linkExpired: "Bu bağlantının süresi doldu.",
    bookingChanged: "Bu rezervasyon, bağlantı gönderildikten sonra değişti. Sohbetinizdeki en son onayı açın.",
    notActive: "Bu rezervasyon artık değiştirilemez.",
    alreadyStarted: "Bu rezervasyon başladı ve burada artık değiştirilemez.",
    taken: "Bu saat az önce doldu. Başka bir saat seçin.",
    closedTime: "Bu saatte kapalı. Başka bir saat seçin.",
    tooMany: "Çok fazla deneme. Bir dakika bekleyip tekrar deneyin.",
    generic: "Bir sorun oluştu. Birazdan tekrar deneyin.",
  },
  ru: {
    pageTitle: "Ваша бронь",
    statusPending: "Ждёт подтверждения",
    statusConfirmed: "Подтверждена",
    statusCancelled: "Отменена",
    statusCompleted: "Состоялась",
    statusNoShow: "Пропущена",
    when: "Когда",
    arrival: "Заезд",
    departure: "Выезд",
    guests: "Гостей",
    service: "Услуга",
    address: "Адрес",
    openMap: "Открыть на карте",
    phone: "Телефон",
    policy: "Условия отмены",
    addToCalendar: "Добавить в календарь",
    writeToUs: "Написать нам",
    chat: "Чат",
    call: "Позвонить",
    change: "Изменить время",
    cancel: "Отменить бронь",
    cancelTitle: "Отменить эту бронь?",
    cancelText: "{business} сразу узнает об этом. Чтобы забронировать снова, просто напишите нам.",
    keep: "Оставить бронь",
    confirmCancel: "Да, отменить",
    cancelling: "Отменяем…",
    cancelledNotice: "Бронь отменена. Мы сообщили об этом: {business}.",
    newTime: "Выберите новое время",
    date: "Дата",
    freeTimes: "Свободное время",
    noTimes: "В этот день нет свободного времени. Выберите другую дату.",
    closedDay: "В этот день закрыто. Выберите другую дату.",
    stayFree: "На ваши даты свободно.",
    stayTaken: "На эти даты занято. Выберите другую дату.",
    loadingTimes: "Ищем свободное время…",
    moveTo: "Перенести: {when}",
    moving: "Переносим…",
    close: "Закрыть",
    movedNotice: "Готово! Бронь перенесена. У этой страницы новый адрес, новая ссылка есть и в вашем чате.",
    overNotice: "Этот визит уже прошёл. Спасибо, что были у нас!",
    startedNotice: "Ваш визит уже начался. Чтобы что-то изменить, напишите нам.",
    errorTitle: "Не удаётся открыть бронь",
    linkInvalid: "Ссылка не работает. Проверьте, что она открыта целиком.",
    linkExpired: "Срок действия ссылки истёк.",
    bookingChanged: "Бронь изменилась после отправки ссылки. Откройте последнее подтверждение в чате.",
    notActive: "Эту бронь уже нельзя изменить.",
    alreadyStarted: "Бронь уже началась, здесь её нельзя изменить.",
    taken: "Это время только что заняли. Выберите другое.",
    closedTime: "В это время закрыто. Выберите другое.",
    tooMany: "Слишком много попыток. Подождите минуту и попробуйте снова.",
    generic: "Что-то пошло не так. Попробуйте ещё раз чуть позже.",
  },
  uk: {
    pageTitle: "Ваше бронювання",
    statusPending: "Очікує підтвердження",
    statusConfirmed: "Підтверджено",
    statusCancelled: "Скасовано",
    statusCompleted: "Відбулося",
    statusNoShow: "Пропущено",
    when: "Коли",
    arrival: "Заїзд",
    departure: "Виїзд",
    guests: "Гостей",
    service: "Послуга",
    address: "Адреса",
    openMap: "Відкрити на мапі",
    phone: "Телефон",
    policy: "Умови скасування",
    addToCalendar: "Додати до календаря",
    writeToUs: "Написати нам",
    chat: "Чат",
    call: "Зателефонувати",
    change: "Змінити час",
    cancel: "Скасувати бронювання",
    cancelTitle: "Скасувати це бронювання?",
    cancelText: "{business} одразу про це дізнається. Щоб забронювати знову, просто напишіть нам.",
    keep: "Залишити бронювання",
    confirmCancel: "Так, скасувати",
    cancelling: "Скасовуємо…",
    cancelledNotice: "Бронювання скасовано. Ми повідомили про це: {business}.",
    newTime: "Оберіть новий час",
    date: "Дата",
    freeTimes: "Вільний час",
    noTimes: "Цього дня немає вільного часу. Оберіть іншу дату.",
    closedDay: "Цього дня зачинено. Оберіть іншу дату.",
    stayFree: "На ваші дати вільно.",
    stayTaken: "На ці дати зайнято. Оберіть іншу дату.",
    loadingTimes: "Шукаємо вільний час…",
    moveTo: "Перенести: {when}",
    moving: "Переносимо…",
    close: "Закрити",
    movedNotice: "Готово! Бронювання перенесено. Ця сторінка має нову адресу, нове посилання є і у вашому чаті.",
    overNotice: "Цей візит уже минув. Дякуємо, що завітали!",
    startedNotice: "Ваш візит уже почався. Щоб щось змінити, напишіть нам.",
    errorTitle: "Не вдається відкрити бронювання",
    linkInvalid: "Посилання не працює. Перевірте, що воно відкрите повністю.",
    linkExpired: "Термін дії посилання минув.",
    bookingChanged: "Бронювання змінилося після надсилання посилання. Відкрийте останнє підтвердження в чаті.",
    notActive: "Це бронювання вже не можна змінити.",
    alreadyStarted: "Бронювання вже почалося, тут його не можна змінити.",
    taken: "Цей час щойно зайняли. Оберіть інший.",
    closedTime: "У цей час зачинено. Оберіть інший.",
    tooMany: "Забагато спроб. Зачекайте хвилину й спробуйте знову.",
    generic: "Щось пішло не так. Спробуйте ще раз трохи згодом.",
  },
};
