/** Booking page texts: English, German, French, Spanish, Italian (see texts.ts). */

import type { BookingPageTexts } from "./texts";

export const TEXTS_WEST: Readonly<Record<string, BookingPageTexts>> = {
  en: {
    pageTitle: "Your booking",
    statusPending: "Awaiting confirmation",
    statusConfirmed: "Confirmed",
    statusCancelled: "Cancelled",
    statusCompleted: "Completed",
    statusNoShow: "Missed",
    when: "When",
    arrival: "Arrival",
    departure: "Departure",
    guests: "Guests",
    service: "Service",
    address: "Address",
    openMap: "Open in maps",
    phone: "Phone",
    policy: "Cancellation policy",
    addToCalendar: "Add to calendar",
    writeToUs: "Write to us",
    chat: "Chat",
    call: "Call",
    change: "Change time",
    cancel: "Cancel booking",
    cancelTitle: "Cancel this booking?",
    cancelText: "{business} will be told at once. To book again, just write to us.",
    keep: "Keep booking",
    confirmCancel: "Yes, cancel",
    cancelling: "Cancelling…",
    cancelledNotice: "Your booking is cancelled. We have let {business} know.",
    newTime: "Choose a new time",
    date: "Date",
    freeTimes: "Free times",
    noTimes: "No free times on this day. Try another date.",
    closedDay: "Closed on this day. Try another date.",
    stayFree: "Free for your dates.",
    stayTaken: "Not free for these dates. Try another date.",
    loadingTimes: "Looking for free times…",
    moveTo: "Move to {when}",
    moving: "Moving…",
    close: "Close",
    movedNotice: "Done! Your booking is moved. This page has a new address, and your chat has the new link.",
    overNotice: "This visit is over. Thank you for coming!",
    startedNotice: "Your visit has started. To change anything, write to us.",
    errorTitle: "This booking cannot be opened",
    linkInvalid: "This link does not work. Check that you opened all of it.",
    linkExpired: "This link has expired.",
    bookingChanged: "This booking was changed after the link was sent. Open the latest confirmation in your chat.",
    notActive: "This booking can no longer be changed.",
    alreadyStarted: "This booking has started and can no longer be changed here.",
    taken: "That time has just been taken. Choose another one.",
    closedTime: "The place is closed at that time. Choose another one.",
    tooMany: "Too many attempts. Wait a minute and try again.",
    generic: "Something went wrong. Try again in a moment.",
  },
  de: {
    pageTitle: "Ihre Buchung",
    statusPending: "Wartet auf Bestätigung",
    statusConfirmed: "Bestätigt",
    statusCancelled: "Storniert",
    statusCompleted: "Abgeschlossen",
    statusNoShow: "Nicht erschienen",
    when: "Wann",
    arrival: "Anreise",
    departure: "Abreise",
    guests: "Personen",
    service: "Leistung",
    address: "Adresse",
    openMap: "In Karten öffnen",
    phone: "Telefon",
    policy: "Stornobedingungen",
    addToCalendar: "Zum Kalender hinzufügen",
    writeToUs: "Schreiben Sie uns",
    chat: "Chat",
    call: "Anrufen",
    change: "Zeit ändern",
    cancel: "Buchung stornieren",
    cancelTitle: "Diese Buchung stornieren?",
    cancelText: "{business} wird sofort informiert. Für eine neue Buchung schreiben Sie uns einfach.",
    keep: "Buchung behalten",
    confirmCancel: "Ja, stornieren",
    cancelling: "Wird storniert…",
    cancelledNotice: "Ihre Buchung ist storniert. Wir haben {business} informiert.",
    newTime: "Neue Zeit wählen",
    date: "Datum",
    freeTimes: "Freie Zeiten",
    noTimes: "An diesem Tag ist nichts frei. Versuchen Sie ein anderes Datum.",
    closedDay: "An diesem Tag geschlossen. Versuchen Sie ein anderes Datum.",
    stayFree: "Für Ihre Daten frei.",
    stayTaken: "Für diese Daten nicht frei. Versuchen Sie ein anderes Datum.",
    loadingTimes: "Freie Zeiten werden gesucht…",
    moveTo: "Verschieben auf {when}",
    moving: "Wird verschoben…",
    close: "Schließen",
    movedNotice: "Erledigt! Ihre Buchung ist verschoben. Diese Seite hat eine neue Adresse, und Ihr Chat hat den neuen Link.",
    overNotice: "Dieser Besuch ist vorbei. Danke für Ihren Besuch!",
    startedNotice: "Ihr Besuch hat begonnen. Für Änderungen schreiben Sie uns.",
    errorTitle: "Diese Buchung lässt sich nicht öffnen",
    linkInvalid: "Dieser Link funktioniert nicht. Prüfen Sie, ob Sie ihn vollständig geöffnet haben.",
    linkExpired: "Dieser Link ist abgelaufen.",
    bookingChanged: "Diese Buchung wurde nach dem Senden des Links geändert. Öffnen Sie die neueste Bestätigung in Ihrem Chat.",
    notActive: "Diese Buchung kann nicht mehr geändert werden.",
    alreadyStarted: "Diese Buchung hat begonnen und kann hier nicht mehr geändert werden.",
    taken: "Diese Zeit wurde gerade vergeben. Wählen Sie eine andere.",
    closedTime: "Zu dieser Zeit ist geschlossen. Wählen Sie eine andere.",
    tooMany: "Zu viele Versuche. Warten Sie eine Minute und versuchen Sie es erneut.",
    generic: "Etwas ist schiefgelaufen. Versuchen Sie es gleich noch einmal.",
  },
  fr: {
    pageTitle: "Votre réservation",
    statusPending: "En attente de confirmation",
    statusConfirmed: "Confirmée",
    statusCancelled: "Annulée",
    statusCompleted: "Terminée",
    statusNoShow: "Manquée",
    when: "Quand",
    arrival: "Arrivée",
    departure: "Départ",
    guests: "Personnes",
    service: "Prestation",
    address: "Adresse",
    openMap: "Voir sur la carte",
    phone: "Téléphone",
    policy: "Conditions d’annulation",
    addToCalendar: "Ajouter au calendrier",
    writeToUs: "Écrivez-nous",
    chat: "Chat",
    call: "Appeler",
    change: "Changer l’heure",
    cancel: "Annuler la réservation",
    cancelTitle: "Annuler cette réservation ?",
    cancelText: "{business} sera prévenu tout de suite. Pour réserver à nouveau, écrivez-nous.",
    keep: "Garder la réservation",
    confirmCancel: "Oui, annuler",
    cancelling: "Annulation…",
    cancelledNotice: "Votre réservation est annulée. Nous avons prévenu {business}.",
    newTime: "Choisir une nouvelle heure",
    date: "Date",
    freeTimes: "Créneaux libres",
    noTimes: "Aucun créneau libre ce jour-là. Essayez une autre date.",
    closedDay: "Fermé ce jour-là. Essayez une autre date.",
    stayFree: "Disponible à vos dates.",
    stayTaken: "Pas disponible à ces dates. Essayez une autre date.",
    loadingTimes: "Recherche des créneaux libres…",
    moveTo: "Déplacer au {when}",
    moving: "Déplacement…",
    close: "Fermer",
    movedNotice: "C’est fait ! Votre réservation est déplacée. Cette page a une nouvelle adresse, et votre chat a le nouveau lien.",
    overNotice: "Cette visite est passée. Merci de votre venue !",
    startedNotice: "Votre visite a commencé. Pour toute modification, écrivez-nous.",
    errorTitle: "Impossible d’ouvrir cette réservation",
    linkInvalid: "Ce lien ne fonctionne pas. Vérifiez que vous l’avez ouvert en entier.",
    linkExpired: "Ce lien a expiré.",
    bookingChanged: "Cette réservation a été modifiée après l’envoi du lien. Ouvrez la dernière confirmation dans votre chat.",
    notActive: "Cette réservation ne peut plus être modifiée.",
    alreadyStarted: "Cette réservation a commencé et ne peut plus être modifiée ici.",
    taken: "Ce créneau vient d’être pris. Choisissez-en un autre.",
    closedTime: "L’établissement est fermé à cette heure-là. Choisissez-en une autre.",
    tooMany: "Trop de tentatives. Attendez une minute et réessayez.",
    generic: "Un problème est survenu. Réessayez dans un instant.",
  },
  es: {
    pageTitle: "Tu reserva",
    statusPending: "Pendiente de confirmación",
    statusConfirmed: "Confirmada",
    statusCancelled: "Cancelada",
    statusCompleted: "Completada",
    statusNoShow: "No asistió",
    when: "Cuándo",
    arrival: "Llegada",
    departure: "Salida",
    guests: "Personas",
    service: "Servicio",
    address: "Dirección",
    openMap: "Ver en el mapa",
    phone: "Teléfono",
    policy: "Política de cancelación",
    addToCalendar: "Añadir al calendario",
    writeToUs: "Escríbenos",
    chat: "Chat",
    call: "Llamar",
    change: "Cambiar la hora",
    cancel: "Cancelar la reserva",
    cancelTitle: "¿Cancelar esta reserva?",
    cancelText: "Avisaremos a {business} enseguida. Para reservar de nuevo, escríbenos.",
    keep: "Mantener la reserva",
    confirmCancel: "Sí, cancelar",
    cancelling: "Cancelando…",
    cancelledNotice: "Tu reserva está cancelada. Hemos avisado a {business}.",
    newTime: "Elige una nueva hora",
    date: "Fecha",
    freeTimes: "Horas libres",
    noTimes: "No hay horas libres ese día. Prueba otra fecha.",
    closedDay: "Cerrado ese día. Prueba otra fecha.",
    stayFree: "Disponible en tus fechas.",
    stayTaken: "No disponible en esas fechas. Prueba otra fecha.",
    loadingTimes: "Buscando horas libres…",
    moveTo: "Cambiar al {when}",
    moving: "Cambiando…",
    close: "Cerrar",
    movedNotice: "¡Listo! Tu reserva se ha cambiado. Esta página tiene una nueva dirección y tu chat tiene el nuevo enlace.",
    overNotice: "Esta visita ya pasó. ¡Gracias por venir!",
    startedNotice: "Tu visita ya empezó. Para cualquier cambio, escríbenos.",
    errorTitle: "No se puede abrir esta reserva",
    linkInvalid: "Este enlace no funciona. Comprueba que lo abriste completo.",
    linkExpired: "Este enlace ha caducado.",
    bookingChanged: "Esta reserva cambió después de enviar el enlace. Abre la confirmación más reciente en tu chat.",
    notActive: "Esta reserva ya no se puede cambiar.",
    alreadyStarted: "Esta reserva ya empezó y no se puede cambiar aquí.",
    taken: "Esa hora se acaba de ocupar. Elige otra.",
    closedTime: "A esa hora está cerrado. Elige otra.",
    tooMany: "Demasiados intentos. Espera un minuto y vuelve a intentarlo.",
    generic: "Algo salió mal. Inténtalo de nuevo en un momento.",
  },
  it: {
    pageTitle: "La tua prenotazione",
    statusPending: "In attesa di conferma",
    statusConfirmed: "Confermata",
    statusCancelled: "Annullata",
    statusCompleted: "Completata",
    statusNoShow: "Mancata",
    when: "Quando",
    arrival: "Arrivo",
    departure: "Partenza",
    guests: "Persone",
    service: "Servizio",
    address: "Indirizzo",
    openMap: "Apri nelle mappe",
    phone: "Telefono",
    policy: "Condizioni di cancellazione",
    addToCalendar: "Aggiungi al calendario",
    writeToUs: "Scrivici",
    chat: "Chat",
    call: "Chiama",
    change: "Cambia orario",
    cancel: "Annulla prenotazione",
    cancelTitle: "Annullare questa prenotazione?",
    cancelText: "{business} verrà avvisato subito. Per prenotare di nuovo, scrivici.",
    keep: "Mantieni la prenotazione",
    confirmCancel: "Sì, annulla",
    cancelling: "Annullamento…",
    cancelledNotice: "La tua prenotazione è annullata. Abbiamo avvisato {business}.",
    newTime: "Scegli un nuovo orario",
    date: "Data",
    freeTimes: "Orari liberi",
    noTimes: "Nessun orario libero in questo giorno. Prova un’altra data.",
    closedDay: "Chiuso in questo giorno. Prova un’altra data.",
    stayFree: "Disponibile per le tue date.",
    stayTaken: "Non disponibile per queste date. Prova un’altra data.",
    loadingTimes: "Cerchiamo orari liberi…",
    moveTo: "Sposta a {when}",
    moving: "Spostamento…",
    close: "Chiudi",
    movedNotice: "Fatto! La tua prenotazione è stata spostata. Questa pagina ha un nuovo indirizzo e la tua chat ha il nuovo link.",
    overNotice: "Questa visita è conclusa. Grazie della visita!",
    startedNotice: "La tua visita è iniziata. Per qualsiasi modifica, scrivici.",
    errorTitle: "Impossibile aprire questa prenotazione",
    linkInvalid: "Questo link non funziona. Controlla di averlo aperto per intero.",
    linkExpired: "Questo link è scaduto.",
    bookingChanged: "Questa prenotazione è cambiata dopo l’invio del link. Apri l’ultima conferma nella tua chat.",
    notActive: "Questa prenotazione non può più essere modificata.",
    alreadyStarted: "Questa prenotazione è iniziata e non può più essere modificata qui.",
    taken: "Quell’orario è appena stato preso. Scegline un altro.",
    closedTime: "A quell’ora il locale è chiuso. Scegline un altro.",
    tooMany: "Troppi tentativi. Attendi un minuto e riprova.",
    generic: "Qualcosa è andato storto. Riprova tra un momento.",
  },
};
