"""
How customers write the numbers one to five, by base language (55
languages), for reading a visit rating written out ("five", "пять",
"ხუთი"). Each entry lists the words for 1, 2, 3, 4 and 5; "|" separates
the forms of one number (genders, colloquial grades such as "пятёрка").
Kept in normalized form: lower case (casefold), NFKC.
"""

from collections.abc import Mapping

NUMBER_WORDS: Mapping[str, tuple[str, str, str, str, str]] = {
    "am": ("አንድ", "ሁለት", "ሶስት|ሦስት", "አራት", "አምስት"),
    "ar": (
        "واحد|واحدة",
        "اثنان|اثنين|اتنين",
        "ثلاثة|ثلاث|تلاتة",
        "أربعة|اربعة|أربع|اربع",
        "خمسة|خمس",
    ),
    "az": ("bir", "iki", "üç", "dörd", "beş"),
    "be": ("адзін|адна", "два|дзве", "тры", "чатыры", "пяць"),
    "bg": ("едно|един|една", "две|два", "три", "четири", "пет"),
    "bn": ("এক", "দুই", "তিন", "চার", "পাঁচ"),
    "bs": ("jedan|jedna", "dva|dvije", "tri", "četiri", "pet"),
    "cs": (
        "jedna|jeden|jednička",
        "dva|dvě|dvojka",
        "tři|trojka",
        "čtyři|čtyřka",
        "pět|pětka",
    ),
    "da": ("en|et|én", "to", "tre", "fire", "fem"),
    "de": ("eins|ein|eine", "zwei", "drei", "vier", "fünf"),
    "el": ("ένα|ένας|μία|μια", "δύο|δυο", "τρία|τρεις", "τέσσερα|τέσσερις", "πέντε"),
    "en": ("one", "two", "three", "four", "five"),
    "es": ("uno|una", "dos", "tres", "cuatro", "cinco"),
    "et": ("üks", "kaks", "kolm", "neli", "viis"),
    "fa": ("یک", "دو", "سه", "چهار", "پنج"),
    "fi": ("yksi", "kaksi", "kolme", "neljä", "viisi"),
    "fr": ("un|une", "deux", "trois", "quatre", "cinq"),
    "he": ("אחת|אחד", "שתיים|שניים|שתים", "שלוש|שלושה", "ארבע|ארבעה", "חמש|חמישה"),
    "hi": ("एक", "दो", "तीन", "चार", "पाँच|पांच"),
    "hr": ("jedan|jedna", "dva|dvije", "tri", "četiri", "pet"),
    "hu": ("egy|egyes", "kettő|két|kettes", "három|hármas", "négy|négyes", "öt|ötös"),
    "hy": ("մեկ", "երկու", "երեք", "չորս", "հինգ"),
    "id": ("satu", "dua", "tiga", "empat", "lima"),
    "is": (
        "einn|eitt|ein",
        "tveir|tvö|tvær",
        "þrír|þrjú|þrjár",
        "fjórir|fjögur",
        "fimm",
    ),
    "it": ("uno|una", "due", "tre", "quattro", "cinque"),
    "ja": (
        "一|いち|ひとつ",
        "二|に|ふたつ",
        "三|さん|みっつ",
        "四|よん|よっつ",
        "五|ご|いつつ",
    ),
    "ka": ("ერთი", "ორი", "სამი", "ოთხი", "ხუთი"),
    "kk": ("бір", "екі", "үш", "төрт", "бес"),
    "ko": ("하나|일", "둘|이", "셋|삼", "넷|사", "다섯|오"),
    "ky": ("бир", "эки", "үч", "төрт", "беш"),
    "lt": ("vienas|viena", "du|dvi", "trys", "keturi|keturios", "penki|penkios"),
    "lv": ("viens|viena", "divi|divas", "trīs", "četri|četras", "pieci|piecas"),
    "mk": ("еден|една", "два|две", "три", "четири", "пет"),
    "mn": ("нэг", "хоёр", "гурав", "дөрөв", "тав"),
    "ms": ("satu", "dua", "tiga", "empat", "lima"),
    "nb": ("en|ett|én", "to", "tre", "fire", "fem"),
    "nl": ("een|één", "twee", "drie", "vier", "vijf"),
    "no": ("en|ett|én", "to", "tre", "fire", "fem"),
    "pl": (
        "jeden|jedna|jedynka",
        "dwa|dwie|dwójka",
        "trzy|trójka",
        "cztery|czwórka",
        "pięć|piątka",
    ),
    "pt": ("um|uma", "dois|duas", "três|tres", "quatro", "cinco"),
    "ro": ("unu|una", "doi|două", "trei", "patru", "cinci"),
    "ru": (
        "один|одна|единица|единичка|кол",
        "два|две|двойка",
        "три|тройка|троечка",
        "четыре|четверка|четвёрка",
        "пять|пятерка|пятёрка|пятёрочка|пятерочка",
    ),
    "sk": (
        "jeden|jedna|jednotka",
        "dva|dve|dvojka",
        "tri|trojka",
        "štyri|štvorka",
        "päť|päťka",
    ),
    "sl": ("ena|en", "dva|dve", "tri", "štiri", "pet"),
    "sq": ("një", "dy", "tre", "katër|kater", "pesë|pese"),
    "sr": (
        "један|једна|jedan|jedna",
        "два|две|dva|dve",
        "три|tri",
        "четири|četiri",
        "пет|pet",
    ),
    "sv": ("ett|en", "två", "tre", "fyra", "fem"),
    "sw": ("moja", "mbili", "tatu", "nne", "tano"),
    "ta": ("ஒன்று", "இரண்டு", "மூன்று", "நான்கு", "ஐந்து"),
    "tg": ("як", "ду", "се", "чор", "панҷ"),
    "th": ("หนึ่ง", "สอง", "สาม", "สี่", "ห้า"),
    "tl": ("isa", "dalawa", "tatlo", "apat", "lima"),
    "tr": ("bir", "iki", "üç", "dört", "beş"),
    "uk": (
        "один|одна|одиниця",
        "два|дві|двійка",
        "три|трійка",
        "чотири|четвірка",
        "п'ять|пʼять|п’ять|пять|пʼятірка|п'ятірка|п’ятірка",
    ),
    "ur": ("ایک", "دو", "تین", "چار", "پانچ"),
    "uz": ("bir", "ikki", "uch", "to'rt|toʻrt|tort", "besh"),
    "vi": ("một|mot", "hai", "ba", "bốn|bon", "năm|nam"),
    "zh": ("一|壹", "二|两|兩|贰", "三|叁", "四|肆", "五|伍"),
}

# Words that may follow a number: "5 stars", "5 звёзд", "5 баллов".
SCORE_UNIT_PREFIXES: tuple[str, ...] = (
    "star",
    "звезд",
    "звёзд",
    "звезды",
    "зір",
    "ვარსკვლავ",
    "աստղ",
    "yıldız",
    "ulduz",
    "stern",
    "étoile",
    "etoile",
    "estrel",
    "stell",
    "gwiazd",
    "hvězd",
    "csillag",
    "stjern",
    "כוכב",
    "نجم",
    "نجوم",
    "ستاره",
    "星",
    "별",
    "point",
    "punkt",
    "punt",
    "puan",
    "pont",
    "балл",
    "бал",
    "ქულ",
    "միավոր",
)

# "4 out of 5" in the languages that say it with a word between.
OUT_OF_WORDS: tuple[str, ...] = (
    "of",
    "out of",
    "из",
    "із",
    "з",
    "iz",
    "z",
    "ze",
    "de",
    "von",
    "sur",
    "su",
    "da",
    "van",
    "av",
    "af",
    "üzerinden",
)
