"""Building a vendored file from its vendor document, writing and comparing it."""

import json
import os
import tempfile
from pathlib import Path
from typing import cast

from scripts.vendor_specs.document_roots import (
    DocumentSchemas,
    openapi_components,
    schemas_of,
)
from scripts.vendor_specs.schema_conversion import SchemaConverter
from scripts.vendor_specs.spec_model import (
    DocumentFormat,
    JsonObject,
    JsonValue,
    RepairSectionReferences,
    VendorSpec,
)
from scripts.vendor_specs.spec_patches import (
    apply_definition_patch,
    describe_patch,
    repair_section_references,
)

JSON_SCHEMA_DIALECT: str = "https://json-schema.org/draft/2020-12/schema"
REFRESH_COMMAND: str = "uv run python -m scripts.refresh_vendor_specs --only {provider}"
# The parts whose change is a change of the vendor's contract; versions and
# notes may move without one.
CONTRACT_KEYS: tuple[str, ...] = ("$defs", "x-roots")
CHECKED_IN_FILE_MODE: int = 0o644


def build_spec_file(
    spec: VendorSpec,
    document: JsonObject,
    version: str,
) -> JsonObject:
    """The vendored file of a spec, from its (downloaded) vendor document."""

    components: dict[str, JsonValue] = (
        openapi_components(document)
        if spec.document_format is DocumentFormat.OPENAPI
        else {}
    )
    for patch in spec.patches:
        if isinstance(patch, RepairSectionReferences):
            components = repair_section_references(components, patch)

    schemas: DocumentSchemas = schemas_of(
        spec.document_format, document, components, spec.roots
    )
    converter = SchemaConverter(schemas.components, schemas.resolve_reference)
    definitions: JsonObject = converter.extract_definitions(schemas.roots)
    for patch in spec.patches:
        if not isinstance(patch, RepairSectionReferences):
            apply_definition_patch(definitions, patch)

    return {
        "$schema": JSON_SCHEMA_DIALECT,
        "$comment": (
            "Generated by scripts/refresh_vendor_specs.py; do not edit by hand "
            "(tests/contracts/README.md)."
        ),
        "x-vendor": {
            "kind": "generated",
            "provider": spec.provider,
            "title": spec.title,
            "source": spec.source_url,
            "format": spec.document_format.value,
            "version": version,
            "patches": [describe_patch(patch) for patch in spec.patches],
            "refresh": REFRESH_COMMAND.format(provider=spec.provider),
        },
        "x-roots": {root.name: root.selector for root in spec.roots},
        "$defs": definitions,
    }


def render(spec_file: JsonObject) -> str:
    """Stable text: sorted keys, one space of indentation, a final newline."""

    return json.dumps(spec_file, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def write_atomically(path: Path, text: str) -> None:
    """Replace the file in one step, so a reader never sees half of it."""

    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as temporary_file:
            temporary_file.write(text)
        # Checked-in files are readable by everyone (mkstemp makes 0600).
        os.chmod(temporary_name, CHECKED_IN_FILE_MODE)
        os.replace(temporary_name, path)
    except BaseException:
        Path(temporary_name).unlink(missing_ok=True)
        raise


def read_spec_file(path: Path) -> JsonObject | None:
    try:
        parsed: object = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None

    return cast(JsonObject, parsed) if isinstance(parsed, dict) else None


def changed_definitions(current: JsonObject | None, fresh: JsonObject) -> list[str]:
    """Names of the definitions and roots that differ (all for a new file)."""

    if current is None:
        return ["(new file)"]

    changed: list[str] = []
    for key in CONTRACT_KEYS:
        old_map: object = current.get(key)
        new_map: object = fresh.get(key)
        old: JsonObject = cast(JsonObject, old_map) if isinstance(old_map, dict) else {}
        new: JsonObject = cast(JsonObject, new_map) if isinstance(new_map, dict) else {}
        changed.extend(
            f"{key}/{name}"
            for name in sorted(set(old) | set(new))
            if old.get(name) != new.get(name)
        )

    return changed
