"""
Write the city that names each time zone in the cabinet's interface
languages (`npm run gen:names` in web/ runs this):

    uv run python -m scripts.export_zone_cities \\
        web/src/lib/zoneCities.generated.ts

The cabinet labels a time zone "Тбилиси (UTC+4)" instead of
"Asia/Tbilisi (UTC+04:00)". Browsers have no Georgian exemplar cities (and
none for some Russian ones), so the names come from the backend's CLDR
data (Babel), like the country and language names of displayNames.

Zones are the IANA "Area/City" names this Python knows (legacy groups such
as US/ or Etc/ are left out). CLDR keys its cities by its own canonical
names (Asia/Calcutta, Europe/Kiev), so a zone is looked up under its
aliases too. English keeps only the cities CLDR spells differently from
the zone's own name (Kyiv); the cabinet derives the rest ("New_York" ->
"New York"). Without a path the module goes to standard output.
"""

import json
import sys
from pathlib import Path
from typing import cast
from zoneinfo import available_timezones

from babel import Locale
from babel.core import get_global

from scripts.export_display_names import INTERFACE_LANGUAGES

LEGACY_GROUPS: tuple[str, ...] = (
    "Etc/",
    "SystemV/",
    "US/",
    "Brazil/",
    "Canada/",
    "Chile/",
    "Mexico/",
)
HEADER: str = """/**
 * The city naming each time zone in the interface languages, from the
 * backend's CLDR data (Babel). Generated by `npm run gen:names`; do not edit.
 */

"""


def zone_names() -> list[str]:
    """IANA "Area/City" zones, without legacy groups, sorted."""

    return sorted(
        zone
        for zone in available_timezones()
        if "/" in zone and not zone.startswith(LEGACY_GROUPS)
    )


def derived_city(zone: str) -> str:
    """The zone's own city: "America/Argentina/Buenos_Aires" -> "Buenos Aires"."""

    return zone.rsplit("/", 1)[-1].replace("_", " ")


def cldr_names_of(zone: str) -> list[str]:
    """The zone and every name CLDR may key it by (its canonical name, aliases)."""

    aliases = cast(dict[str, str], get_global("zone_aliases"))
    canonical: str = aliases.get(zone, zone)
    linked: list[str] = [
        alias for alias, target in aliases.items() if target in (zone, canonical)
    ]
    return [zone, canonical, *linked]


def city_of(zone: str, names: dict[str, dict[str, object]]) -> str | None:
    """The CLDR city of a zone in one language, or None (none or the zone's own)."""

    for name in cldr_names_of(zone):
        city: object = names.get(name, {}).get("city")
        if isinstance(city, str):
            return None if city == derived_city(zone) else city
    return None


def export_zone_cities() -> str:
    """The TypeScript module with zone cities per interface language."""

    lines: list[str] = [
        "export const ZONE_CITIES: Readonly<Record<string, Readonly<Record<string, "
        "string>>>> = {"
    ]
    for interface_language in INTERFACE_LANGUAGES:
        names = cast(
            dict[str, dict[str, object]], Locale.parse(interface_language).time_zones
        )
        lines.append(f"  {interface_language}: {{")
        for zone in zone_names():
            city: str | None = city_of(zone, names)
            if city is not None:
                lines.append(
                    f"    {json.dumps(zone)}: {json.dumps(city, ensure_ascii=False)},"
                )
        lines.append("  },")

    lines.append("};")
    return HEADER + "\n".join(lines) + "\n"


def main(arguments: list[str]) -> None:
    module: str = export_zone_cities()
    if not arguments:
        sys.stdout.write(module)
        return

    Path(arguments[0]).write_text(module, encoding="utf-8")


if __name__ == "__main__":
    main(sys.argv[1:])
