"""
Write the digits after the decimal point of every currency for the cabinet
(`npm run gen:currencies` in web/ runs this):

    uv run python -m scripts.export_currency_digits \\
        web/src/lib/currencyDigits.generated.ts

The API sends money in minor units. The cabinet converts them with the same
CLDR table the backend uses (Babel), not with the browser's Intl data, which
differs between browser versions (rupiah: 2 digits in one CLDR release, 0 in
the next), so a price is never shown or saved 100 times off.

Without a path the module goes to standard output.
"""

import sys
from pathlib import Path

from babel.numbers import get_currency_precision, list_currencies

HEADER: str = """/**
 * Digits after the decimal point of each currency, from the backend's CLDR
 * data (Babel). Generated by `npm run gen:currencies`; do not edit.
 */

export const CURRENCY_MINOR_DIGITS: Readonly<Record<string, number>> = {
"""


def export_currency_digits() -> str:
    """The TypeScript module with every currency's minor-unit digits."""

    lines: list[str] = [
        f"  {code}: {get_currency_precision(code)},"
        for code in sorted(list_currencies())
        if code.isalpha() and code.isupper() and len(code) == 3
    ]
    return HEADER + "\n".join(lines) + "\n};\n"


def main(arguments: list[str]) -> None:
    module: str = export_currency_digits()
    if not arguments:
        sys.stdout.write(module)
        return

    Path(arguments[0]).write_text(module, encoding="utf-8")


if __name__ == "__main__":
    main(sys.argv[1:])
