"""
Write country and language names in the cabinet's interface languages
(`npm run gen:names` in web/ runs this):

    uv run python -m scripts.export_display_names \\
        web/src/lib/displayNames.generated.ts

The cabinet names countries and languages with the same CLDR data the
backend uses (Babel), not with the browser's Intl.DisplayNames: Chrome
ships display names only for its own interface languages, which do not
include Georgian, so a Georgian owner saw "GE" instead of "საქართველო", and
the page rendered on the server (full ICU) did not match the browser
(a hydration error).

Languages are those of the backend's language registry; regions are the
two-letter CLDR territories. Without a path the module goes to standard
output.
"""

import json
import sys
from pathlib import Path
from typing import cast

from babel import Locale

from app.registries.localization.language_registry import LanguageRegistry

# The cabinet's interface languages (web/src/i18n/config.ts, LOCALES).
INTERFACE_LANGUAGES: tuple[str, ...] = ("en", "ru", "ka")
HEADER: str = """/**
 * Country and language names in the interface languages, from the backend's
 * CLDR data (Babel). Generated by `npm run gen:names`; do not edit.
 */

"""


def export_display_names() -> str:
    """The TypeScript module with region and language names per locale."""

    language_tags: list[str] = sorted(
        str(language.tag) for language in LanguageRegistry().list_all()
    )
    regions: dict[str, dict[str, str]] = {}
    languages: dict[str, dict[str, str]] = {}
    for interface_language in INTERFACE_LANGUAGES:
        locale: Locale = Locale.parse(interface_language)
        territory_names = cast(dict[str, str], locale.territories)
        language_names = cast(dict[str, str], locale.languages)
        regions[interface_language] = {
            code: str(name)
            for code, name in sorted(territory_names.items())
            if len(code) == 2 and code.isalpha() and code.isupper()
        }
        languages[interface_language] = {
            tag: str(language_names[key])
            for tag in language_tags
            if (key := tag.replace("-", "_")) in language_names
        }

    return (
        HEADER
        + render_table("REGION_NAMES", regions)
        + "\n"
        + render_table("LANGUAGE_NAMES", languages)
    )


def render_table(name: str, table: dict[str, dict[str, str]]) -> str:
    lines: list[str] = [
        f"export const {name}: Readonly<Record<string, Readonly<Record<string, "
        "string>>>> = {"
    ]
    for interface_language, names in table.items():
        lines.append(f"  {interface_language}: {{")
        lines.extend(
            f"    {json.dumps(code)}: {json.dumps(text, ensure_ascii=False)},"
            for code, text in names.items()
        )
        lines.append("  },")

    lines.append("};")
    return "\n".join(lines) + "\n"


def main(arguments: list[str]) -> None:
    module: str = export_display_names()
    if not arguments:
        sys.stdout.write(module)
        return

    Path(arguments[0]).write_text(module, encoding="utf-8")


if __name__ == "__main__":
    main(sys.argv[1:])
