/** Information panel texts of the hosted chat page: the Middle East, South and East Asia (see infoTexts.ts). */

import type { HostedInfoTexts } from "./infoTexts";

export const INFO_TEXTS_ASIA: Readonly<Record<string, HostedInfoTexts>> = {
  he: {
    openNow: "פתוח עכשיו",
    closedNow: "סגור עכשיו",
    openAllDay: "פתוח 24 שעות",
    until: "עד {time}",
    opensAt: "נפתח ב-{time}",
    opensTomorrow: "נפתח מחר ב-{time}",
    opensOn: "נפתח ב{day} ב-{time}",
    hours: "שעות פתיחה",
    closed: "סגור",
    address: "כתובת",
    openMap: "פתיחה במפה",
    book: "הזמנה",
    bookPrompt: "שלום! אני רוצה להזמין.",
    details: "שעות וכתובת",
  },
  ar: {
    openNow: "مفتوح الآن",
    closedNow: "مغلق الآن",
    openAllDay: "مفتوح على مدار الساعة",
    until: "حتى {time}",
    opensAt: "يفتح الساعة {time}",
    opensTomorrow: "يفتح غدًا الساعة {time}",
    opensOn: "يفتح يوم {day} الساعة {time}",
    hours: "ساعات العمل",
    closed: "مغلق",
    address: "العنوان",
    openMap: "فتح في الخرائط",
    book: "احجز",
    bookPrompt: "مرحبًا! أود الحجز.",
    details: "الساعات والعنوان",
  },
  fa: {
    openNow: "اکنون باز است",
    closedNow: "اکنون بسته است",
    openAllDay: "شبانه‌روزی باز است",
    until: "تا {time}",
    opensAt: "ساعت {time} باز می‌شود",
    opensTomorrow: "فردا ساعت {time} باز می‌شود",
    opensOn: "{day} ساعت {time} باز می‌شود",
    hours: "ساعات کاری",
    closed: "بسته",
    address: "نشانی",
    openMap: "باز کردن در نقشه",
    book: "رزرو",
    bookPrompt: "سلام! می‌خواهم رزرو کنم.",
    details: "ساعات و نشانی",
  },
  ur: {
    openNow: "ابھی کھلا ہے",
    closedNow: "ابھی بند ہے",
    openAllDay: "24 گھنٹے کھلا ہے",
    until: "{time} تک",
    opensAt: "{time} بجے کھلے گا",
    opensTomorrow: "کل {time} بجے کھلے گا",
    opensOn: "{day} کو {time} بجے کھلے گا",
    hours: "اوقاتِ کار",
    closed: "بند",
    address: "پتہ",
    openMap: "نقشے میں کھولیں",
    book: "بکنگ کریں",
    bookPrompt: "السلام علیکم! مجھے بکنگ کرنی ہے۔",
    details: "اوقات اور پتہ",
  },
  hi: {
    openNow: "अभी खुला है",
    closedNow: "अभी बंद है",
    openAllDay: "24 घंटे खुला",
    until: "{time} तक",
    opensAt: "{time} बजे खुलेगा",
    opensTomorrow: "कल {time} बजे खुलेगा",
    opensOn: "{day} को {time} बजे खुलेगा",
    hours: "खुलने का समय",
    closed: "बंद",
    address: "पता",
    openMap: "मैप में खोलें",
    book: "बुक करें",
    bookPrompt: "नमस्ते! मुझे बुकिंग करनी है।",
    details: "समय और पता",
  },
  zh: {
    openNow: "营业中",
    closedNow: "已打烊",
    openAllDay: "24 小时营业",
    until: "营业至 {time}",
    opensAt: "{time} 开门",
    opensTomorrow: "明天 {time} 开门",
    opensOn: "{day} {time} 开门",
    hours: "营业时间",
    closed: "休息",
    address: "地址",
    openMap: "在地图中打开",
    book: "预订",
    bookPrompt: "您好！我想预订。",
    details: "营业时间和地址",
  },
  ja: {
    openNow: "営業中",
    closedNow: "営業時間外",
    openAllDay: "24時間営業",
    until: "{time}まで",
    opensAt: "{time}に開店",
    opensTomorrow: "明日{time}に開店",
    opensOn: "{day}{time}に開店",
    hours: "営業時間",
    closed: "定休日",
    address: "住所",
    openMap: "地図で開く",
    book: "予約する",
    bookPrompt: "こんにちは！予約をお願いします。",
    details: "営業時間と住所",
  },
  ko: {
    openNow: "영업 중",
    closedNow: "영업 종료",
    openAllDay: "24시간 영업",
    until: "{time}까지",
    opensAt: "{time}에 영업 시작",
    opensTomorrow: "내일 {time}에 영업 시작",
    opensOn: "{day} {time}에 영업 시작",
    hours: "영업시간",
    closed: "휴무",
    address: "주소",
    openMap: "지도에서 열기",
    book: "예약하기",
    bookPrompt: "안녕하세요! 예약하고 싶어요.",
    details: "영업시간 및 주소",
  },
  vi: {
    openNow: "Đang mở cửa",
    closedNow: "Đã đóng cửa",
    openAllDay: "Mở cửa 24 giờ",
    until: "đến {time}",
    opensAt: "mở cửa lúc {time}",
    opensTomorrow: "mở cửa ngày mai lúc {time}",
    opensOn: "mở cửa {day} lúc {time}",
    hours: "Giờ mở cửa",
    closed: "Đóng cửa",
    address: "Địa chỉ",
    openMap: "Mở trong bản đồ",
    book: "Đặt chỗ",
    bookPrompt: "Xin chào! Tôi muốn đặt chỗ.",
    details: "Giờ mở cửa và địa chỉ",
  },
};
