/** Information panel texts of the hosted chat page: Western and Northern Europe (see infoTexts.ts). */

import type { HostedInfoTexts } from "./infoTexts";

export const INFO_TEXTS_WEST: Readonly<Record<string, HostedInfoTexts>> = {
  en: {
    openNow: "Open now",
    closedNow: "Closed now",
    openAllDay: "Open 24 hours",
    until: "until {time}",
    opensAt: "opens at {time}",
    opensTomorrow: "opens tomorrow at {time}",
    opensOn: "opens {day} at {time}",
    hours: "Opening hours",
    closed: "Closed",
    address: "Address",
    openMap: "Open in maps",
    book: "Book",
    bookPrompt: "Hello! I'd like to book.",
    details: "Hours and address",
  },
  de: {
    openNow: "Jetzt geöffnet",
    closedNow: "Jetzt geschlossen",
    openAllDay: "24 Stunden geöffnet",
    until: "bis {time}",
    opensAt: "öffnet um {time}",
    opensTomorrow: "öffnet morgen um {time}",
    opensOn: "öffnet am {day} um {time}",
    hours: "Öffnungszeiten",
    closed: "Geschlossen",
    address: "Adresse",
    openMap: "In Karten öffnen",
    book: "Buchen",
    bookPrompt: "Hallo! Ich möchte gern buchen.",
    details: "Öffnungszeiten und Adresse",
  },
  fr: {
    openNow: "Ouvert",
    closedNow: "Fermé",
    openAllDay: "Ouvert 24 h/24",
    until: "jusqu’à {time}",
    opensAt: "ouvre à {time}",
    opensTomorrow: "ouvre demain à {time}",
    opensOn: "ouvre {day} à {time}",
    hours: "Horaires d’ouverture",
    closed: "Fermé",
    address: "Adresse",
    openMap: "Voir sur la carte",
    book: "Réserver",
    bookPrompt: "Bonjour ! Je voudrais réserver.",
    details: "Horaires et adresse",
  },
  es: {
    openNow: "Abierto ahora",
    closedNow: "Cerrado ahora",
    openAllDay: "Abierto 24 horas",
    until: "hasta las {time}",
    opensAt: "abre a las {time}",
    opensTomorrow: "abre mañana a las {time}",
    opensOn: "abre el {day} a las {time}",
    hours: "Horario",
    closed: "Cerrado",
    address: "Dirección",
    openMap: "Ver en el mapa",
    book: "Reservar",
    bookPrompt: "¡Hola! Quisiera hacer una reserva.",
    details: "Horario y dirección",
  },
  it: {
    openNow: "Aperto ora",
    closedNow: "Chiuso ora",
    openAllDay: "Aperto 24 ore su 24",
    until: "fino alle {time}",
    opensAt: "apre alle {time}",
    opensTomorrow: "apre domani alle {time}",
    opensOn: "apre {day} alle {time}",
    hours: "Orari di apertura",
    closed: "Chiuso",
    address: "Indirizzo",
    openMap: "Apri nelle mappe",
    book: "Prenota",
    bookPrompt: "Ciao! Vorrei prenotare.",
    details: "Orari e indirizzo",
  },
  pt: {
    openNow: "Aberto agora",
    closedNow: "Fechado agora",
    openAllDay: "Aberto 24 horas",
    until: "até às {time}",
    opensAt: "abre às {time}",
    opensTomorrow: "abre amanhã às {time}",
    opensOn: "abre {day} às {time}",
    hours: "Horário de funcionamento",
    closed: "Fechado",
    address: "Endereço",
    openMap: "Abrir no mapa",
    book: "Reservar",
    bookPrompt: "Olá! Gostaria de fazer uma reserva.",
    details: "Horário e endereço",
  },
  pl: {
    openNow: "Teraz otwarte",
    closedNow: "Teraz zamknięte",
    openAllDay: "Otwarte całą dobę",
    until: "do {time}",
    opensAt: "otwarcie o {time}",
    opensTomorrow: "otwarcie jutro o {time}",
    opensOn: "otwarcie: {day}, {time}",
    hours: "Godziny otwarcia",
    closed: "Zamknięte",
    address: "Adres",
    openMap: "Otwórz w mapach",
    book: "Zarezerwuj",
    bookPrompt: "Dzień dobry! Chcę zarezerwować.",
    details: "Godziny i adres",
  },
  lt: {
    openNow: "Dabar atidaryta",
    closedNow: "Dabar uždaryta",
    openAllDay: "Atidaryta visą parą",
    until: "iki {time}",
    opensAt: "atidaroma {time}",
    opensTomorrow: "atidaroma rytoj {time}",
    opensOn: "atidaroma: {day}, {time}",
    hours: "Darbo laikas",
    closed: "Uždaryta",
    address: "Adresas",
    openMap: "Atidaryti žemėlapyje",
    book: "Rezervuoti",
    bookPrompt: "Sveiki! Norėčiau rezervuoti.",
    details: "Darbo laikas ir adresas",
  },
  lv: {
    openNow: "Šobrīd atvērts",
    closedNow: "Šobrīd slēgts",
    openAllDay: "Atvērts visu diennakti",
    until: "līdz {time}",
    opensAt: "atver {time}",
    opensTomorrow: "atver rīt {time}",
    opensOn: "atver: {day}, {time}",
    hours: "Darba laiks",
    closed: "Slēgts",
    address: "Adrese",
    openMap: "Atvērt kartē",
    book: "Rezervēt",
    bookPrompt: "Labdien! Vēlos rezervēt.",
    details: "Darba laiks un adrese",
  },
  et: {
    openNow: "Praegu avatud",
    closedNow: "Praegu suletud",
    openAllDay: "Avatud ööpäev läbi",
    until: "kuni {time}",
    opensAt: "avatakse kell {time}",
    opensTomorrow: "avatakse homme kell {time}",
    opensOn: "avatakse: {day}, kell {time}",
    hours: "Lahtiolekuajad",
    closed: "Suletud",
    address: "Aadress",
    openMap: "Ava kaardil",
    book: "Broneeri",
    bookPrompt: "Tere! Sooviksin broneerida.",
    details: "Lahtiolekuajad ja aadress",
  },
  fi: {
    openNow: "Avoinna nyt",
    closedNow: "Suljettu nyt",
    openAllDay: "Avoinna ympäri vuorokauden",
    until: "klo {time} asti",
    opensAt: "avautuu klo {time}",
    opensTomorrow: "avautuu huomenna klo {time}",
    opensOn: "avautuu: {day} klo {time}",
    hours: "Aukioloajat",
    closed: "Suljettu",
    address: "Osoite",
    openMap: "Avaa kartalla",
    book: "Varaa",
    bookPrompt: "Hei! Haluaisin tehdä varauksen.",
    details: "Aukioloajat ja osoite",
  },
  nb: {
    openNow: "Åpent nå",
    closedNow: "Stengt nå",
    openAllDay: "Åpent døgnet rundt",
    until: "til {time}",
    opensAt: "åpner kl. {time}",
    opensTomorrow: "åpner i morgen kl. {time}",
    opensOn: "åpner {day} kl. {time}",
    hours: "Åpningstider",
    closed: "Stengt",
    address: "Adresse",
    openMap: "Åpne i kart",
    book: "Bestill",
    bookPrompt: "Hei! Jeg vil gjerne bestille.",
    details: "Åpningstider og adresse",
  },
};
