/** Information panel texts of the hosted chat page: Eastern Europe, the Caucasus, Turkey and Central Asia (see infoTexts.ts). */

import type { HostedInfoTexts } from "./infoTexts";

export const INFO_TEXTS_CENTRAL: Readonly<Record<string, HostedInfoTexts>> = {
  ru: {
    openNow: "Сейчас открыто",
    closedNow: "Сейчас закрыто",
    openAllDay: "Открыто круглосуточно",
    until: "до {time}",
    opensAt: "откроется в {time}",
    opensTomorrow: "откроется завтра в {time}",
    opensOn: "откроется: {day}, {time}",
    hours: "Часы работы",
    closed: "Закрыто",
    address: "Адрес",
    openMap: "Открыть на карте",
    book: "Забронировать",
    bookPrompt: "Здравствуйте! Хочу забронировать.",
    details: "Часы работы и адрес",
  },
  uk: {
    openNow: "Зараз відчинено",
    closedNow: "Зараз зачинено",
    openAllDay: "Працює цілодобово",
    until: "до {time}",
    opensAt: "відчиниться о {time}",
    opensTomorrow: "відчиниться завтра о {time}",
    opensOn: "відчиниться: {day}, {time}",
    hours: "Години роботи",
    closed: "Зачинено",
    address: "Адреса",
    openMap: "Відкрити на мапі",
    book: "Забронювати",
    bookPrompt: "Вітаю! Хочу забронювати.",
    details: "Години роботи та адреса",
  },
  kk: {
    openNow: "Қазір ашық",
    closedNow: "Қазір жабық",
    openAllDay: "Тәулік бойы ашық",
    until: "{time} дейін",
    opensAt: "{time} ашылады",
    opensTomorrow: "ертең {time} ашылады",
    opensOn: "{day}, {time} ашылады",
    hours: "Жұмыс уақыты",
    closed: "Жабық",
    address: "Мекенжай",
    openMap: "Картадан ашу",
    book: "Брондау",
    bookPrompt: "Сәлеметсіз бе! Брондағым келеді.",
    details: "Жұмыс уақыты мен мекенжай",
  },
  ka: {
    openNow: "ახლა ღიაა",
    closedNow: "ახლა დაკეტილია",
    openAllDay: "ღიაა 24 საათი",
    until: "{time}-მდე",
    opensAt: "გაიხსნება {time}-ზე",
    opensTomorrow: "გაიხსნება ხვალ {time}-ზე",
    opensOn: "გაიხსნება: {day}, {time}",
    hours: "სამუშაო საათები",
    closed: "დაკეტილია",
    address: "მისამართი",
    openMap: "რუკაზე გახსნა",
    book: "დაჯავშნა",
    bookPrompt: "გამარჯობა! მინდა დავჯავშნო.",
    details: "საათები და მისამართი",
  },
  hy: {
    openNow: "Հիմա բաց է",
    closedNow: "Հիմա փակ է",
    openAllDay: "Բաց է շուրջօրյա",
    until: "մինչև {time}",
    opensAt: "կբացվի ժամը {time}-ին",
    opensTomorrow: "կբացվի վաղը՝ ժամը {time}-ին",
    opensOn: "կբացվի՝ {day}, {time}",
    hours: "Աշխատանքային ժամեր",
    closed: "Փակ է",
    address: "Հասցե",
    openMap: "Բացել քարտեզում",
    book: "Ամրագրել",
    bookPrompt: "Բարև ձեզ։ Ուզում եմ ամրագրել։",
    details: "Ժամեր և հասցե",
  },
  az: {
    openNow: "Hazırda açıqdır",
    closedNow: "Hazırda bağlıdır",
    openAllDay: "24 saat açıqdır",
    until: "{time}-dək",
    opensAt: "saat {time}-da açılır",
    opensTomorrow: "sabah saat {time}-da açılır",
    opensOn: "açılır: {day}, {time}",
    hours: "İş saatları",
    closed: "Bağlıdır",
    address: "Ünvan",
    openMap: "Xəritədə aç",
    book: "Rezerv et",
    bookPrompt: "Salam! Rezerv etmək istəyirəm.",
    details: "İş saatları və ünvan",
  },
  tr: {
    openNow: "Şu an açık",
    closedNow: "Şu an kapalı",
    openAllDay: "24 saat açık",
    until: "{time} saatine kadar",
    opensAt: "{time} saatinde açılıyor",
    opensTomorrow: "yarın {time} saatinde açılıyor",
    opensOn: "açılış: {day}, {time}",
    hours: "Çalışma saatleri",
    closed: "Kapalı",
    address: "Adres",
    openMap: "Haritada aç",
    book: "Rezervasyon yap",
    bookPrompt: "Merhaba! Rezervasyon yapmak istiyorum.",
    details: "Çalışma saatleri ve adres",
  },
  uz: {
    openNow: "Hozir ochiq",
    closedNow: "Hozir yopiq",
    openAllDay: "Kecha-kunduz ochiq",
    until: "{time} gacha",
    opensAt: "soat {time} da ochiladi",
    opensTomorrow: "ertaga soat {time} da ochiladi",
    opensOn: "ochiladi: {day}, {time}",
    hours: "Ish vaqti",
    closed: "Yopiq",
    address: "Manzil",
    openMap: "Xaritada ochish",
    book: "Band qilish",
    bookPrompt: "Salom! Band qilmoqchi edim.",
    details: "Ish vaqti va manzil",
  },
};
