/** Hosted chat page and table card texts: European languages (see texts.ts). */

import type { HostedChatTexts } from "./texts";

export const TEXTS_EUROPE: Readonly<Record<string, HostedChatTexts>> = {
  en: {
    loading: "Opening the chat…",
    unavailable: "This chat is not available right now.",
    tryLater: "Please try again later.",
    noScript: "Turn on JavaScript to use this chat.",
    notFound: "There is no chat at this address. Check the link.",
    scanToChat: "Scan to chat with us",
    cardHint: "Ask us anything — we reply right away.",
  },
  de: {
    loading: "Chat wird geöffnet…",
    unavailable: "Dieser Chat ist gerade nicht verfügbar.",
    tryLater: "Bitte versuchen Sie es später noch einmal.",
    noScript: "Aktivieren Sie JavaScript, um diesen Chat zu nutzen.",
    notFound: "Unter dieser Adresse gibt es keinen Chat. Prüfen Sie den Link.",
    scanToChat: "Scannen und mit uns chatten",
    cardHint: "Fragen Sie uns alles – wir antworten sofort.",
  },
  fr: {
    loading: "Ouverture du chat…",
    unavailable: "Ce chat n’est pas disponible pour le moment.",
    tryLater: "Veuillez réessayer plus tard.",
    noScript: "Activez JavaScript pour utiliser ce chat.",
    notFound: "Aucun chat à cette adresse. Vérifiez le lien.",
    scanToChat: "Scannez pour discuter avec nous",
    cardHint: "Posez-nous vos questions, nous répondons tout de suite.",
  },
  es: {
    loading: "Abriendo el chat…",
    unavailable: "Este chat no está disponible en este momento.",
    tryLater: "Inténtalo de nuevo más tarde.",
    noScript: "Activa JavaScript para usar este chat.",
    notFound: "No hay ningún chat en esta dirección. Revisa el enlace.",
    scanToChat: "Escanea para chatear con nosotros",
    cardHint: "Pregúntanos lo que quieras: respondemos al instante.",
  },
  it: {
    loading: "Apertura della chat…",
    unavailable: "Questa chat non è disponibile al momento.",
    tryLater: "Riprova più tardi.",
    noScript: "Attiva JavaScript per usare questa chat.",
    notFound: "Non c’è nessuna chat a questo indirizzo. Controlla il link.",
    scanToChat: "Inquadra per chattare con noi",
    cardHint: "Chiedici qualsiasi cosa: rispondiamo subito.",
  },
  pt: {
    loading: "Abrindo o chat…",
    unavailable: "Este chat não está disponível no momento.",
    tryLater: "Tente novamente mais tarde.",
    noScript: "Ative o JavaScript para usar este chat.",
    notFound: "Não há nenhum chat neste endereço. Verifique o link.",
    scanToChat: "Escaneie para conversar conosco",
    cardHint: "Pergunte o que quiser — respondemos na hora.",
  },
  pl: {
    loading: "Otwieranie czatu…",
    unavailable: "Ten czat jest teraz niedostępny.",
    tryLater: "Spróbuj ponownie później.",
    noScript: "Włącz JavaScript, aby korzystać z tego czatu.",
    notFound: "Pod tym adresem nie ma czatu. Sprawdź link.",
    scanToChat: "Zeskanuj i napisz do nas",
    cardHint: "Zapytaj o cokolwiek — odpowiadamy od razu.",
  },
  lt: {
    loading: "Atidaromas pokalbis…",
    unavailable: "Šis pokalbis šiuo metu nepasiekiamas.",
    tryLater: "Bandykite dar kartą vėliau.",
    noScript: "Įjunkite „JavaScript“, kad galėtumėte naudotis šiuo pokalbiu.",
    notFound: "Šiuo adresu pokalbio nėra. Patikrinkite nuorodą.",
    scanToChat: "Nuskenuokite ir parašykite mums",
    cardHint: "Klauskite bet ko – atsakome iš karto.",
  },
  lv: {
    loading: "Atver tērzēšanu…",
    unavailable: "Šī tērzēšana pašlaik nav pieejama.",
    tryLater: "Lūdzu, mēģiniet vēlāk vēlreiz.",
    noScript: "Ieslēdziet JavaScript, lai izmantotu šo tērzēšanu.",
    notFound: "Šajā adresē nav tērzēšanas. Pārbaudiet saiti.",
    scanToChat: "Noskenējiet un rakstiet mums",
    cardHint: "Jautājiet mums jebko – atbildam uzreiz.",
  },
  et: {
    loading: "Vestlus avaneb…",
    unavailable: "See vestlus pole praegu saadaval.",
    tryLater: "Palun proovige hiljem uuesti.",
    noScript: "Selle vestluse kasutamiseks lülitage JavaScript sisse.",
    notFound: "Sellel aadressil vestlust pole. Kontrollige linki.",
    scanToChat: "Skannige ja kirjutage meile",
    cardHint: "Küsige meilt mida tahes – vastame kohe.",
  },
  fi: {
    loading: "Avataan keskustelua…",
    unavailable: "Tämä keskustelu ei ole juuri nyt käytettävissä.",
    tryLater: "Yritä myöhemmin uudelleen.",
    noScript: "Ota JavaScript käyttöön käyttääksesi tätä keskustelua.",
    notFound: "Tässä osoitteessa ei ole keskustelua. Tarkista linkki.",
    scanToChat: "Skannaa ja keskustele kanssamme",
    cardHint: "Kysy meiltä mitä tahansa – vastaamme heti.",
  },
  nb: {
    loading: "Åpner chatten…",
    unavailable: "Denne chatten er ikke tilgjengelig akkurat nå.",
    tryLater: "Prøv igjen senere.",
    noScript: "Slå på JavaScript for å bruke denne chatten.",
    notFound: "Det finnes ingen chat på denne adressen. Sjekk lenken.",
    scanToChat: "Skann for å chatte med oss",
    cardHint: "Spør oss om hva som helst – vi svarer med en gang.",
  },
  ru: {
    loading: "Открываем чат…",
    unavailable: "Этот чат сейчас недоступен.",
    tryLater: "Попробуйте позже.",
    noScript: "Включите JavaScript, чтобы пользоваться этим чатом.",
    notFound: "По этому адресу чата нет. Проверьте ссылку.",
    scanToChat: "Отсканируйте, чтобы написать нам",
    cardHint: "Спрашивайте что угодно — ответим сразу.",
  },
  uk: {
    loading: "Відкриваємо чат…",
    unavailable: "Цей чат зараз недоступний.",
    tryLater: "Спробуйте пізніше.",
    noScript: "Увімкніть JavaScript, щоб користуватися цим чатом.",
    notFound: "За цією адресою чату немає. Перевірте посилання.",
    scanToChat: "Скануйте, щоб написати нам",
    cardHint: "Питайте будь-що — відповімо одразу.",
  },
};
