/** Hosted chat page and table card texts: Caucasus, Central Asia, Middle East, Asia (see texts.ts). */

import type { HostedChatTexts } from "./texts";

export const TEXTS_ASIA: Readonly<Record<string, HostedChatTexts>> = {
  kk: {
    loading: "Чат ашылып жатыр…",
    unavailable: "Бұл чат қазір қолжетімсіз.",
    tryLater: "Кейінірек қайталап көріңіз.",
    noScript: "Бұл чатты пайдалану үшін JavaScript қосыңыз.",
    notFound: "Бұл мекенжайда чат жоқ. Сілтемені тексеріңіз.",
    scanToChat: "Бізге жазу үшін сканерлеңіз",
    cardHint: "Кез келген сұрақ қойыңыз — бірден жауап береміз.",
  },
  ka: {
    loading: "ჩატი იხსნება…",
    unavailable: "ეს ჩატი ახლა მიუწვდომელია.",
    tryLater: "გთხოვთ, სცადოთ მოგვიანებით.",
    noScript: "ამ ჩატით სარგებლობისთვის ჩართეთ JavaScript.",
    notFound: "ამ მისამართზე ჩატი არ არის. შეამოწმეთ ბმული.",
    scanToChat: "დაასკანერეთ და მოგვწერეთ",
    cardHint: "გვკითხეთ ნებისმიერი რამ — მაშინვე გიპასუხებთ.",
  },
  hy: {
    loading: "Զրուցարանը բացվում է…",
    unavailable: "Այս զրուցարանն այժմ հասանելի չէ։",
    tryLater: "Խնդրում ենք փորձել ավելի ուշ։",
    noScript: "Միացրեք JavaScript-ը՝ այս զրուցարանից օգտվելու համար։",
    notFound: "Այս հասցեով զրուցարան չկա։ Ստուգեք հղումը։",
    scanToChat: "Սկանավորեք և գրեք մեզ",
    cardHint: "Հարցրեք մեզ ցանկացած բան․ կպատասխանենք անմիջապես։",
  },
  az: {
    loading: "Çat açılır…",
    unavailable: "Bu çat hazırda əlçatan deyil.",
    tryLater: "Zəhmət olmasa, sonra yenidən cəhd edin.",
    noScript: "Bu çatdan istifadə etmək üçün JavaScript-i aktiv edin.",
    notFound: "Bu ünvanda çat yoxdur. Linki yoxlayın.",
    scanToChat: "Bizə yazmaq üçün skan edin",
    cardHint: "Bizdən istədiyinizi soruşun — dərhal cavab veririk.",
  },
  tr: {
    loading: "Sohbet açılıyor…",
    unavailable: "Bu sohbet şu anda kullanılamıyor.",
    tryLater: "Lütfen daha sonra tekrar deneyin.",
    noScript: "Bu sohbeti kullanmak için JavaScript'i açın.",
    notFound: "Bu adreste bir sohbet yok. Bağlantıyı kontrol edin.",
    scanToChat: "Bize yazmak için tarayın",
    cardHint: "Bize her şeyi sorun — hemen yanıtlıyoruz.",
  },
  uz: {
    loading: "Chat ochilmoqda…",
    unavailable: "Bu chat hozir mavjud emas.",
    tryLater: "Keyinroq qayta urinib ko‘ring.",
    noScript: "Bu chatdan foydalanish uchun JavaScript’ni yoqing.",
    notFound: "Bu manzilda chat yo‘q. Havolani tekshiring.",
    scanToChat: "Bizga yozish uchun skanerlang",
    cardHint: "Bizdan istalgan narsani so‘rang — darhol javob beramiz.",
  },
  he: {
    loading: "פותחים את הצ׳אט…",
    unavailable: "הצ׳אט הזה לא זמין כרגע.",
    tryLater: "נסו שוב מאוחר יותר.",
    noScript: "הפעילו JavaScript כדי להשתמש בצ׳אט הזה.",
    notFound: "אין צ׳אט בכתובת הזו. בדקו את הקישור.",
    scanToChat: "סרקו כדי לכתוב לנו",
    cardHint: "שאלו אותנו כל דבר — אנחנו עונים מיד.",
  },
  ar: {
    loading: "جارٍ فتح المحادثة…",
    unavailable: "هذه المحادثة غير متاحة الآن.",
    tryLater: "يُرجى المحاولة لاحقًا.",
    noScript: "فعّل JavaScript لاستخدام هذه المحادثة.",
    notFound: "لا توجد محادثة على هذا العنوان. تحقّق من الرابط.",
    scanToChat: "امسح الرمز لمراسلتنا",
    cardHint: "اسألنا عن أي شيء، نرد عليك فورًا.",
  },
  fa: {
    loading: "در حال باز کردن گفتگو…",
    unavailable: "این گفتگو اکنون در دسترس نیست.",
    tryLater: "لطفاً بعداً دوباره امتحان کنید.",
    noScript: "برای استفاده از این گفتگو، JavaScript را روشن کنید.",
    notFound: "در این نشانی گفتگویی وجود ندارد. پیوند را بررسی کنید.",
    scanToChat: "برای پیام دادن به ما اسکن کنید",
    cardHint: "هر سؤالی دارید بپرسید؛ فوراً پاسخ می‌دهیم.",
  },
  ur: {
    loading: "چیٹ کھل رہی ہے…",
    unavailable: "یہ چیٹ ابھی دستیاب نہیں ہے۔",
    tryLater: "براہ کرم بعد میں دوبارہ کوشش کریں۔",
    noScript: "اس چیٹ کو استعمال کرنے کے لیے JavaScript آن کریں۔",
    notFound: "اس پتے پر کوئی چیٹ نہیں ہے۔ لنک چیک کریں۔",
    scanToChat: "ہمیں لکھنے کے لیے اسکین کریں",
    cardHint: "ہم سے کچھ بھی پوچھیں، ہم فوراً جواب دیتے ہیں۔",
  },
  hi: {
    loading: "चैट खुल रही है…",
    unavailable: "यह चैट अभी उपलब्ध नहीं है।",
    tryLater: "कृपया बाद में फिर से कोशिश करें।",
    noScript: "इस चैट का इस्तेमाल करने के लिए JavaScript चालू करें।",
    notFound: "इस पते पर कोई चैट नहीं है। लिंक जाँचें।",
    scanToChat: "हमसे चैट करने के लिए स्कैन करें",
    cardHint: "हमसे कुछ भी पूछें — हम तुरंत जवाब देते हैं।",
  },
  zh: {
    loading: "正在打开聊天…",
    unavailable: "此聊天暂时不可用。",
    tryLater: "请稍后再试。",
    noScript: "请启用 JavaScript 以使用此聊天。",
    notFound: "此地址没有聊天。请检查链接。",
    scanToChat: "扫码与我们聊天",
    cardHint: "有任何问题都可以问我们，我们会立即回复。",
  },
  ja: {
    loading: "チャットを開いています…",
    unavailable: "このチャットは現在ご利用いただけません。",
    tryLater: "しばらくしてからもう一度お試しください。",
    noScript: "このチャットを使うには JavaScript を有効にしてください。",
    notFound: "このアドレスにはチャットがありません。リンクをご確認ください。",
    scanToChat: "スキャンしてチャットで質問",
    cardHint: "何でもお気軽にどうぞ。すぐにお返事します。",
  },
  ko: {
    loading: "채팅을 여는 중…",
    unavailable: "지금은 이 채팅을 사용할 수 없습니다.",
    tryLater: "잠시 후 다시 시도해 주세요.",
    noScript: "이 채팅을 사용하려면 JavaScript를 켜 주세요.",
    notFound: "이 주소에는 채팅이 없습니다. 링크를 확인해 주세요.",
    scanToChat: "스캔해서 채팅으로 문의하세요",
    cardHint: "무엇이든 물어보세요. 바로 답해 드립니다.",
  },
  vi: {
    loading: "Đang mở cuộc trò chuyện…",
    unavailable: "Cuộc trò chuyện này hiện không khả dụng.",
    tryLater: "Vui lòng thử lại sau.",
    noScript: "Hãy bật JavaScript để dùng cuộc trò chuyện này.",
    notFound: "Không có cuộc trò chuyện nào ở địa chỉ này. Hãy kiểm tra lại liên kết.",
    scanToChat: "Quét mã để nhắn tin cho chúng tôi",
    cardHint: "Hỏi chúng tôi bất cứ điều gì — chúng tôi trả lời ngay.",
  },
};
