import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      "react-hooks/exhaustive-deps": "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-console": ["error", { allow: ["warn", "error"] }],
      // Zod without its eval-based JIT (src/lib/zod.ts): the CSP forbids eval.
      "no-restricted-imports": [
        "error",
        { paths: [{ name: "zod", message: 'Import { z } from "@/lib/zod" (no eval under the CSP).' }] },
      ],
    },
  },
  {
    // Many small files that each do a little: at most 300 lines, counting
    // every line (blank lines and comments too). Generated files are exempt.
    files: ["src/**/*.{ts,tsx,mts}", "e2e/**/*.{ts,tsx,mts}"],
    ignores: ["src/**/*.generated.ts"],
    rules: {
      "max-lines": ["error", { max: 300, skipBlankLines: false, skipComments: false }],
    },
  },
  {
    // The landing's 3D scene (react-three-fiber): useFrame callbacks run in the
    // render loop, outside React's render, and move three.js objects in place
    // (positions, uniforms, scene.environment) by design. The React Compiler's
    // immutability check cannot tell those callbacks from render code.
    files: ["src/app/_landing/scene/**/*.{ts,tsx}"],
    rules: { "react-hooks/immutability": "off" },
  },
  {
    // Dates and times in a UI language come from lib/intl (Georgian in every
    // browser) through lib/format.ts with an explicit time zone: a format
    // without one takes the zone of whatever runs it, so the server and the
    // browser write different text and hydration fails (React #418).
    files: ["src/**/*.{ts,tsx,mts}"],
    ignores: ["src/lib/intl/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "NewExpression[callee.object.name='Intl'][callee.property.name='DateTimeFormat']",
          message: "Use formatDateTime/formatDate/formatTime (lib/format) with a timeZone, or lib/intl/calendarFields.",
        },
        {
          selector: "CallExpression[callee.object.name='Intl'][callee.property.name='DateTimeFormat']",
          message: "Use formatDateTime/formatDate/formatTime (lib/format) with a timeZone, or lib/intl/calendarFields.",
        },
        {
          selector: "CallExpression[callee.property.name=/^toLocale(Date|Time)?String$/]",
          message: "toLocale*String formats in the zone and language of whatever runs it; use lib/format with a timeZone.",
        },
      ],
    },
  },
  {
    // Playwright fixtures receive a `use` callback that is not React's `use`.
    files: ["e2e/**/*.ts"],
    rules: { "react-hooks/rules-of-hooks": "off" },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    // Generated by `npm run gen:api`.
    "src/api/schema.d.ts",
    "e2e/.artifacts/**",
  ]),
]);

export default eslintConfig;
