import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // useApiQuery(fetcher, deps) takes a dependency list like useEffect.
      "react-hooks/exhaustive-deps": [
        "error",
        { additionalHooks: "(useApiQuery)" },
      ],
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-console": ["error", { allow: ["warn", "error"] }],
    },
  },
  {
    // Playwright fixtures receive a `use` callback that is not React's `use`.
    files: ["e2e/**/*.ts"],
    rules: { "react-hooks/rules-of-hooks": "off" },
  },
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    // Generated by `npm run gen:api`.
    "src/api/schema.d.ts",
    "e2e/.artifacts/**",
  ]),
]);

export default eslintConfig;
